
use role accountadmin;
use warehouse compute_wh;


/*
    Warehouse 사용 비용 확인

    참고 사항
        - ACCOUNT_USAGE 와 같은 메타데이터 정보는 조회 시 비용 발생하지 않음
*/

-- 전월 비용 확인
SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS TOTAL_CLOUD_SERVICES,
    SUM(CREDITS_USED_COMPUTE) AS TOTAL_COMPUTE
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('MONTH', -1, DATE_TRUNC('MONTH', CURRENT_DATE())) 
AND START_TIME < DATE_TRUNC('MONTH', CURRENT_DATE())
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;


-- 특정 Warehouse 일별 비용 확인
SELECT
    DATE_TRUNC('DAY', START_TIME) || '  ' || DAYNAME(DATE_TRUNC('DAY', START_TIME)) AS USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP)
AND WAREHOUSE_NAME = 'CDC_WH'
GROUP BY 1, 2
ORDER BY 1 DESC, 3 DESC;



-- 비용을 많이 사용한 SQL 확인
SELECT
    -- QUERY_ID,
    -- WAREHOUSE_NAME,
    -- USER_NAME,
    -- TOTAL_ELAPSED_TIME/1000 AS SECONDS
    *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP)
AND WAREHOUSE_NAME = 'CDC_WH'
LIMIT 50;


select * from SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY limit 10;
