
use role accountadmin;
use warehouse compute_wh;


/*
    SnowPipe 사용 비용 확인
*/


-- 전월 비용 확인
SELECT
    PIPE_NAME,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
WHERE START_TIME >= DATEADD('MONTH', -1, DATE_TRUNC('MONTH', CURRENT_DATE())) 
AND START_TIME < DATE_TRUNC('MONTH', CURRENT_DATE())
GROUP BY PIPE_NAME
ORDER BY TOTAL_CREDITS DESC;



-- 특정 Pipe 일별 비용 확인
SELECT
    DATE_TRUNC('DAY', START_TIME) || '  ' || DAYNAME(DATE_TRUNC('DAY', START_TIME)) AS USAGE_DATE,
    PIPE_NAME,
    SUM(CREDITS_USED) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP)
AND PIPE_NAME = 'HTSML01_CARD_MASTER_MST'
GROUP BY 1, 2
ORDER BY 1 DESC, 3 DESC;



