
use role accountadmin;
use warehouse compute_wh;


/*
    Storage 공간 확인
*/


-- 전체 저장 공간 확인
SELECT
    ROUND(SUM(STORAGE_BYTES)/1024/1024/1024,2) AS STORAGE_GB,
    ROUND(SUM(STAGE_BYTES)/1024/1024/1024,2) AS STAGE_GB,
    ROUND(SUM(FAILSAFE_BYTES)/1024/1024/1024,2) AS FAILSAFE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE;


-- Database 별 저장 공간 확인
SELECT
    USAGE_DATE,
    DATABASE_NAME,
    ROUND(AVERAGE_DATABASE_BYTES/1024/1024/1024,2) AS STORAGE_GB,
    ROUND(AVERAGE_FAILSAFE_BYTES/1024/1024/1024,2) AS FAILSAFE_GB,
    ROUND(AVERAGE_HYBRID_TABLE_STORAGE_BYTES/1024/1024/1024,2) AS HYBRID_TABLE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE = CURRENT_DATE()
ORDER BY STORAGE_GB DESC;


-- Stage 저장 공간 확인
SELECT
    USAGE_DATE,
    ROUND(AVERAGE_STAGE_BYTES/1024/1024/1024,2) AS STAGE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.STAGE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE = CURRENT_DATE()
;