-- CREATE USER H2640
--   PASSWORD = 'HanaTour123!@#'
--   LOGIN_NAME = 'H2640'
--   DISPLAY_NAME = '문형서'
--   EMAIL = 'ronny213@hanatour.com'
--   DEFAULT_ROLE = rl_all_r
--   MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE rl_all_r TO USER h2640_it;
GRANT ROLE rl_it_div TO USER h2640_it;
ALTER USER H2640 SET DEFAULT_ROLE = 'USERADMIN';
ALTER USER H2640 SET DISABLE_MFA = TRUE;
------------------------------------------------------------------
CREATE USER H2640_IT
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'H2640_IT'
  DISPLAY_NAME = '문형서'
  EMAIL = 'ronny213@hanatour.com'
  DEFAULT_ROLE = rl_all_r
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE rl_all_r TO USER h2640_it;
GRANT ROLE rl_it_div TO USER h2640_it;
ALTER USER H2640_IT SET DEFAULT_ROLE = 'RL_IT_DIV';

CREATE USER HG448
  PASSWORD = 'HanaTour12##'
  LOGIN_NAME = 'HG448'
  DISPLAY_NAME = '강용'
  EMAIL = 'kdragon@hanatour.com'
  DEFAULT_ROLE = sysadmin
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE sysadmin TO USER HG448;

-- GRANT ROLE rl_customer_div TO USER h2640_cust;
-- ALTER USER H2640_CUST SET DEFAULT_ROLE = 'RL_CUSTOMER_DIV';

---------------------------------------------------------------------
GRANT USAGE ON DATABASE DWDM TO ROLE rl_dbt_func_rw;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE DWDM TO ROLE rl_dbt_func_rw;

GRANT USAGE ON DATABASE SYS_DBT TO USER H2122;
GRANT USAGE ON SCHEMA SYS_DBT.YK TO USER H2122;
GRANT CREATE DBT PROJECT ON SCHEMA SYS_DBT.YK TO USER H2122; --x
-- revoke USAGE ON DATABASE SYS_DBT from USER H2122;
-- revoke USAGE ON SCHEMA SYS_DBT.YK from USER H2122;