use role sysadmin;

-- use database cdc;
-- CREATE SCHEMA IF NOT EXISTS AIR01 ;
-- CREATE SCHEMA IF NOT EXISTS CHL01 ;
-- CREATE SCHEMA IF NOT EXISTS COM01 ;
-- CREATE SCHEMA IF NOT EXISTS CST01 ;
-- CREATE SCHEMA IF NOT EXISTS HCS01 ;
-- CREATE SCHEMA IF NOT EXISTS HGSIN01 ;
-- CREATE SCHEMA IF NOT EXISTS HTL01 ;
-- CREATE SCHEMA IF NOT EXISTS HTSAC01 ;
-- CREATE SCHEMA IF NOT EXISTS HTSBR01 ;
-- CREATE SCHEMA IF NOT EXISTS HTSIN01 ;
-- CREATE SCHEMA IF NOT EXISTS HTSML01 ;
-- CREATE SCHEMA IF NOT EXISTS HTSOT01 ;
-- CREATE SCHEMA IF NOT EXISTS HUB01 ;
-- CREATE SCHEMA IF NOT EXISTS PKG01 ;
-- CREATE SCHEMA IF NOT EXISTS STT01 ;

use database SYS_DBT;
create schema PROJECT2;


use database SECURITY;
create schema MHS_POLICY;