/*
  This file was automatically generated by dbt
 
        Source: models/marts/inf01/G_SEQ_07_04_BASE_SA_DAY/dwdm_inf01__ibsa_onln_qtsh_m.sql
      Compiled: target/compiled/models/marts/inf01/G_SEQ_07_04_BASE_SA_DAY/dwdm_inf01__ibsa_onln_qtsh_m.sql
  Last updated: 2026. 1. 13. 오후 6:20:58
*/
 
 
 
 
 
/* 변경적재 파라미터 */
    WITH PARAM AS
    (
      SELECT TO_DATE('20250909', 'yyyyMMddHH24MISS') AS P_ETL_STRT_D
           , TO_DATE('20250910' , 'yyyyMMddHH24MISS') AS P_ETL_END_D
           , '20250909'                              AS P_ETL_STRT_D_CHAR
           , '20250910'                               AS P_ETL_END_D_CHAR
      FROM DUAL
    ),
    /* 변경적재 조건 START */
    W_TAB AS
    (
        SELECT M01.QUOT_SRN
        FROM   cdc.pkg01.rsv_pkg_quot_m          M01 /* IWPK_패키지견적기본 */
              ,PARAM                          T99 /* 파라메타 */
        WHERE  M01.UPD_DTTM >= T99.P_ETL_STRT_D AND M01.UPD_DTTM < T99.P_ETL_END_D
         
        UNION
        
        SELECT M02.QUOT_SRN
        FROM   cdc.pkg01.rsv_pkg_quot_d          M02 /* IWPK_패키지견적상세 */
              ,PARAM                          T99 /* 파라메타 */
        WHERE  M02.UPD_DTTM >= T99.P_ETL_STRT_D AND M02.UPD_DTTM < T99.P_ETL_END_D
    
        UNION
      
        SELECT M03.QUOT_SRN
        FROM   cdc.pkg01.rsv_pkg_quot_mgr_m      M03 /* IWPK_패키지견적관리자기본 */
              ,PARAM                          T99 /* 파라메타 */
        WHERE M03.UPD_DTTM >= T99.P_ETL_STRT_D AND M03.UPD_DTTM < T99.P_ETL_END_D
    
        UNION
      
        SELECT M04.QUOT_SRN
        FROM   cdc.pkg01.rsv_pkg_quot_ansr_send_h M04 /* IWPK_패키지견적답변발송이력 */
              ,PARAM                          T99 /* 파라메타 */
        WHERE M04.UPD_DTTM >= T99.P_ETL_STRT_D AND M04.UPD_DTTM < T99.P_ETL_END_D
    )
    SELECT  S1.QUOT_SRN                                                                                                                AS QUOT_SRN             /* 견적일련번호 */
           ,S2.QUOT_DTL_SEQ                                                                                                            AS QUOT_DTL_SEQ         /* 견적순번 */
           ,NVL(S2.QUOT_STAT_CD,'~')                                                                                                   AS QUOT_STAT_CD         /* 견적상태코드 */  -- COM_COM_DTL_C(QUOT_STAT_CD)
           ,NVL(S2.CNTG_STAT_CD,'~')                                                                                                   AS CNTG_STAT_CD         /* 체결상태코드 */  -- COM_COM_DTL_C(CNTG_STAT_CD)
           ,NVL(S1.COM_AREA_CD,'~')                                                                                                    AS COM_AREA_CD          /* 공통지역코드 */  -- COM_COM_DTL_C(RPPR_SSC_CD)
           ,NVL(S2.NMOP_SCALE_CD,'~')                                                                                                  AS NMOP_SCALE_CD        /* 인원규모코드 */  -- 10, 20, 30, 50, 100, U1H(100이상)
           ,S2.DEP_DT                                                                                                                  AS DEP_DT               /* 출발일자 */
           ,S2.ARR_DT                                                                                                                  AS ARR_DT               /* 도착일자 */
           ,S1.COM_QUOT_KND_CD                                                                                                         AS QUOT_KND_CD          /* 견적종류코드 */  -- COM_COM_DTL_C(COM_QUOT_KND_CD)
           ,NVL(S1.QUOT_DV_CD,'~')                                                                                                     AS QUOT_DV_CD           /* 견적구분코드 */  -- Y N C
           ,S1.TITL_NM                                                                                                                 AS TITL_NM              /* 제목명 */
           ,S1.INP_DTTM                                                                                                                AS INP_DTTM             /* 입록일시 */
           ,S1.INPR_ID                                                                                                                 AS RGSR_EMPN            /* 등록자사원번호 */ -- IWCM_EMP_M,IWCM_PTN_STAF_D,IWCM_UNFY_USR_M
           ,COALESCE(  (SELECT DEPT_CD FROM cdc.com01.com_emp_m      WHERE EMPN    = S1.INPR_ID)
                      ,(SELECT PTN_CD  FROM cdc.com01.sch_ptn_staf_d WHERE STAF_CD = S1.INPR_ID)
                      ,(SELECT DEPT_CD FROM cdc.com01.usr_unfy_usr_m WHERE USRID   = S1.INPR_ID)
                      , '~'
                    )                                                                                                                  AS QUOT_RGSR_TEAM_CD    /* 등록자팀코드 */
           ,NVL(S5.HANA_MRPPR_EMPN,'~')                                                                                                AS HANA_MRPPR_EMPN      /* 영업사원번호 */
           ,NVL(S5.HANA_MRPPR_TEAM_CD,'~')                                                                                             AS HANA_MRPPR_TEAM_CD   /* 영업팀코드 */
           ,NVL(S5.INCTV_RPPR_ID,'~')                                                                                                  AS INCTV_RPPR_ID        /* 인센티브OP(주)담당자ID */
           ,NVL(S5.INCTV_RSPB_DEPT_CD,'~')                                                                                             AS INCTV_RSPB_DEPT_CD   /* 인센티브OP(주)담당자부서코드 */
           ,NVL(S3.RPPR_EMPN,'~')                                                                                                      AS ANSR_MRPPR_EMPN      /* 주답변자사원번호 */
           ,NVL(S3.RPPR_DEPT_CD,'~')                                                                                                   AS ANSR_MRPPR_TEAM_CD   /* 주답변자팀코드 */
           ,NVL(S4.RPPR_EMPN,'~')                                                                                                      AS ANSR_SRPPR_EMPN      /* 부답변자사원번호 */
           ,NVL(S4.RPPR_DEPT_CD,'~')                                                                                                   AS ANSR_SRPPR_TEAM_CD   /* 부답변자팀코드 */
           ,NVL(S5.AGT_CD,'~')                                                                                                         AS AGT_CD               /* 대리점코드 */
           ,NVL(S5.CTRC_REL_CD,'~')                                                                                                    AS CTRC_REL_CD          /* 계약관계코드 */
           ,NVL(S1.TRVL_PUPS_CD,'~')                                                                                                   AS TRVL_PUPS_CD         /* 여행목적코드 */  -- COM_COM_DTL_C(TRVL_PUPS_CD)
           ,NVL(S1.CUST_TYPE_1_CD,'~')                                                                                                 AS CUST_TYPE_1_CD       /* 고객유형1코드 */ -- COM_COM_DTL_C(CUST_TYPE_1_CD)
           ,NVL(S1.CUST_TYPE_2_CD,'~')                                                                                                 AS CUST_TYPE_2_CD       /* 고객유형2코드 */ -- COM_COM_DTL_C(CUST_TYPE_2_CD)
           ,NVL(CRPN_SRN,'~')                                                                                                          AS CRPN_SRN             /* 법인일련번호 */
           ,S1.CRPN_CTI_YN                                                                                                             AS CRPN_CTI_YN          /* 법인CTI여부 */
           ,S1.INCTV_CRTT_YN                                                                                                           AS INCTV_CRTT_YN        /* 인센티브인증여부 */
           ,S1.BIDN_YN                                                                                                                 AS BIDN_YN              /* 입찰여부 */
           ,NVL(S1.GRP_MDOR_TRVL_YN,'~')                                                                                               AS GRP_MDOR_TRVL_YN     /* 그룹맞춤여행여부 */
           ,NVL(S1.PDEP_CD,'~')                                                                                                        AS PDEP_CD              /* 출발지(공항) 코드 */ --COM_COM_DTL_C(PDEP_CD)
           ,NVL(S7.TRVL_NOP,0)                                                                                                         AS TRVL_NOP             /* 여행인원수 */
           ,S2.LAST_ANSR_DTTM                                                                                                          AS LAST_ANSR_DTTM       /* 최종답변일시 */
           ,NVL(S2.LAST_ANSR_EMPN,'~')                                                                                                 AS LAST_ANSR_EMPN       /* 최종답변사원번호 */
        --  , CASE WHEN S8.SEND_DTTM < S2.INP_DTTM THEN NULL /* 견적입력일시보다 답변일시가 빠른경우 */
        --         ELSE
        --              (SELECT
        --                      SUM(CASE WHEN TO_CHAR(S2.INP_DTTM + (LEVEL - 1)/24/60,'YYYYMMDD') IN (
        --                       SELECT YMD_CD FROM DWDM.inf01.IBCO_DT_C WHERE GREATEST(NVL(HLDY_YN,'N'), NVL(WEND_YN,'N')) = 'N') --휴일제외
        --                               THEN 1
        --                               ELSE 0
        --                          END)
        --                FROM DUAL
        --               WHERE 1=1
        --                 AND TO_CHAR(S2.INP_DTTM + (LEVEL - 1)/24/60,'HH24MI') BETWEEN '0900' AND '1200' /* 오전근무시간 */
        --                  OR TO_CHAR(S2.INP_DTTM + (LEVEL - 1)/24/60,'HH24MI') BETWEEN '1300' AND '1800' /* 오후근무시간 */
        --               CONNECT BY LEVEL <= (S8.SEND_DTTM - S2.INP_DTTM) * (24*60))
        --     END                                                                                                                        AS ANSR_RQRM_NOM        /* 답변소요분수 */
           ,CURRENT_TIMESTAMP()                                                                                                                    AS ETL_RGST_DTTM        /* ETL 등록일시 */
           ,'INF_ETL'                                                                                    AS ETL_RGSR_ID          /* ETL 등록자 */
           ,'S_IBSA_ONLN_QTSH_M'                                                                                                   AS ETL_RGST_PRGM_ID     /* ETL 등록프로그램 */
           ,CURRENT_TIMESTAMP()                                                                                                                    AS ETL_UPD_DTTM         /* ETL 변경일시 */
           ,'INF_ETL'                                                                                    AS ETL_UPDR_ID          /* ETL 변경자 */
           ,'S_IBSA_ONLN_QTSH_M'                                                                                                   AS ETL_UPD_PRGM_ID      /* ETL 변경프로그램 */
    FROM   cdc.pkg01.rsv_pkg_quot_m                                                                    S1 /* IWPK_패키지견적기본 */
                                                                                                                                       
    INNER JOIN cdc.pkg01.rsv_pkg_quot_d                                                                S2 /* IWPK_패키지견적상세 */
    ON S1.QUOT_SRN = S2.QUOT_SRN                                                                                                       
                                                                                                                                       
    LEFT OUTER JOIN cdc.pkg01.rsv_pkg_quot_mgr_m                                                       S3 /* IWPK_패키지견적관리자기본 - 주답변자 */
    ON S1.QUOT_SRN = S3.QUOT_SRN AND S3.RPPR_TYPE_CD ='AS1'                                                                            
                                                                                                                                       
    LEFT OUTER JOIN cdc.pkg01.rsv_pkg_quot_mgr_m                                                       S4 /* IWPK_패키지견적관리자기본 - 부답변자 */
    ON S1.QUOT_SRN = S4.QUOT_SRN AND S4.RPPR_TYPE_CD ='AS2'
    
    LEFT OUTER JOIN
    (
         SELECT S51.QUOT_SRN                                                                    AS QUOT_SRN             /* 견적번호 */                   
               ,S51.RPPR_EMPN                                                                   AS AGT_EMPN             /* 대리점 담당자사원번호 */  -- COM_EMP_M
               ,S51.RPPR_DEPT_CD                                                                AS AGT_CD               /* 대리점코드 */          
               ,S52.CTRC_REL_CD                                                                 AS CTRC_REL_CD          /* 대리점 계약관계코드 */
               ,S53.RPPR_EMPN                                                                   AS HANA_MRPPR_EMPN      /* 담당세일즈사원번호 */    -- COM_EMP_M
               ,S53.RPPR_DEPT_CD                                                                AS HANA_MRPPR_TEAM_CD   /* 담당세일즈부서코드 */    -- COM_DEPT_C
               ,S54.SPVS_RPPR_ID                                                                AS INCTV_RPPR_ID        /* 인센OP(정) 사원번호 */  -- COM_EMP_M
               ,S54.SPVS_RPPR_DEPT_CD                                                           AS INCTV_RSPB_DEPT_CD   /* 인센OP(정) 부서코드 */  -- COM_DEPT_C
         FROM  cdc.pkg01.rsv_pkg_quot_mgr_m                     S51 /* IWPK_패키지견적관리자기본 */
         INNER JOIN cdc.com01.sch_agt_d                         S52 /* IWCM_대리점상세 */
         ON    S51.RPPR_DEPT_CD = S52.PTN_CD AND S51.RPPR_TYPE_CD ='JIC'           
         LEFT OUTER JOIN cdc.com01.sch_ptn_rppr_r               S53 /* IWCM_거래처담당자관계 */
         ON    S51.RPPR_DEPT_CD = S53.PTN_CD AND S53.RPPR_ROLE_CD = 'HNPA'         
         LEFT OUTER JOIN cdc.com01.sch_agt_pkg_sals_rspb_d      S54 /* IWCM_대리점패키지영업담당상세 */
         ON    S51.RPPR_DEPT_CD = S54.PTN_CD AND S54.RSPB_AREA_CD = 'Q1'                         
    )                                                                                                                                  S5  /* IWPK_패키지견적관리자기본 - 대리점/세일즈/인센OP */
    ON S1.QUOT_SRN = S5.QUOT_SRN
    
    LEFT OUTER JOIN
    (
         SELECT QUOT_SRN, QUOT_DTL_SEQ, SUM(TO_NUMBER(QUOT_DMND_VAL)) AS TRVL_NOP
         FROM   cdc.pkg01.rsv_pkg_quot_dmnd_d
         WHERE  QUOT_DMND_DV_CD = 'AGE_LRG_CD'
         AND    QUOT_DMND_INFO_CD IN ('A','C','I')
         GROUP BY QUOT_SRN, QUOT_DTL_SEQ
    )                                                                                                                                  S7 /* IWPK_패키지견적요청상세 */
    ON S2.QUOT_SRN = S7.QUOT_SRN AND S2.QUOT_DTL_SEQ = S7.QUOT_DTL_SEQ                           
                                                                                                 
    LEFT OUTER JOIN cdc.pkg01.rsv_pkg_quot_ansr_send_h                                                  S8 /* IWPK_패키지견적답변발송이력 */
    ON  (     S2.QUOT_SRN = S8.QUOT_SRN
          AND S2.QUOT_DTL_SEQ = NVL(S8.QUOT_DTL_SEQ, S2.QUOT_DTL_SEQ)
          AND S8.ANSR_SEND_SEQ = 1
        )
        
    INNER JOIN W_TAB                                                                                                                   S99 /*모수지정*/
    ON S1.QUOT_SRN = S99.QUOT_SRN    