use database SYS_DBT;
use schema YK;
USE ROLE rl_dbt_user;
CREATE DBT PROJECT HNT_DP_YK999 FROM $$snow://workspace/USER$H2122.PUBLIC.DEFAULT$/versions/live/HNT_DP_YK$$ DEFAULT_TARGET = 'dev';

-- create or replace dbt project SYS_DBT.YK.HNT_DP998 from @SYS_DBT.YK.DBT_PROJECT_HNT_DP_1763953275_STAGE;
SELECT CURRENT_ROLE(), CURRENT_USER();
SHOW GRANTS ON DATABASE SYS_DBT;
SHOW GRANTS ON SCHEMA SYS_DBT.YK;
SHOW GRANTS TO ROLE rl_dbt_user;

CREATE TABLE SYS_DBT.YK.test_dbt (col1 varchar(10));
