use role useradmin;
-------------------------------------------------------------------------------------------------------------
SHOW GRANTS TO ROLE rl_dbt_func_rw;
-------------------------------------------------------------------------------------------------------------
CREATE ROLE rl_dbt_func_rw COMMENT = 'DBT Functional 권한';

GRANT USAGE ON WAREHOUSE compute_wh TO ROLE rl_dbt_func_rw;
GRANT USAGE ON WAREHOUSE dbt_execute_wh TO ROLE rl_dbt_func_rw;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;

GRANT USAGE, CREATE SCHEMA, MODIFY ON DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;

GRANT USAGE ON DATABASE HANALOG TO ROLE rl_dbt_func_rw;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HANALOG TO ROLE rl_dbt_func_rw;
GRANT SELECT ON ALL TABLES IN DATABASE HANALOG TO ROLE rl_dbt_func_rw;
GRANT SELECT ON FUTURE TABLES IN DATABASE HANALOG TO ROLE rl_dbt_func_rw;

GRANT USAGE ON DATABASE TMS TO ROLE rl_dbt_func_rw;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TMS TO ROLE rl_dbt_func_rw;
GRANT SELECT ON ALL TABLES IN DATABASE TMS TO ROLE rl_dbt_func_rw;
GRANT SELECT ON FUTURE TABLES IN DATABASE TMS TO ROLE rl_dbt_func_rw;

GRANT USAGE ON DATABASE CDC TO ROLE rl_dbt_func_rw;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CDC TO ROLE rl_dbt_func_rw;
GRANT SELECT ON ALL TABLES IN DATABASE CDC TO ROLE rl_dbt_func_rw;
GRANT SELECT ON FUTURE TABLES IN DATABASE CDC TO ROLE rl_dbt_func_rw;

GRANT USAGE, CREATE SCHEMA, MODIFY ON DATABASE DWDM TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE DWDM TO ROLE rl_dbt_func_rw WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE DWDM TO ROLE rl_dbt_func_rw WITH GRANT OPTION;

-- test
-- GRANT alter ON ALL TABLES IN DATABASE DWDM TO ROLE rl_dbt_func_rw; --x
-- GRANT alter ON ALL TABLES IN SCHEMA DWDM.INF01 TO ROLE rl_dbt_func_rw; --x
-- GRANT alter ON TABLE IN SCHEMA DWDM.INF01 TO ROLE rl_dbt_func_rw;
-- GRANT alter ON TABLE DWDM.INF01.IBCO_ETC_BSC_C TO ROLE rl_dbt_func_rw; --x
-- GRANT modify ON ALL SCHEMAS IN DATABASE DWDM TO ROLE rl_dbt_func_rw; --testing // 실행실패
-- grant role sysadmin to ROLE rl_dbt_func_rw; --이건 성공
-- revoke role sysadmin from ROLE rl_dbt_func_rw;
GRANT modify ON DATABASE DWDM TO ROLE rl_dbt_func_rw; --testing // 실행실패
GRANT modify ON SCHEMA DWDM.INF01 TO ROLE rl_dbt_func_rw; --testing // 실행실패
GRANT USAGE ON SCHEMA DWDM.INF01 TO ROLE rl_dbt_func_rw; --testing // 실행실패
-- GRANT modify ON TABLE DWDM.INF01.IBCO_ETC_BSC_C TO ROLE rl_dbt_func_rw; --x

GRANT USAGE ON DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE INT_DWDM TO ROLE rl_dbt_func_rw;

-------------------------------------------------------------------------------------------------------
CREATE ROLE rl_dbt_user COMMENT = 'DBT user 권한';

GRANT ROLE rl_dbt_func_rw TO ROLE rl_dbt_user;
GRANT ROLE rl_dbt_user TO USER H2640_IT;
GRANT ROLE rl_dbt_user TO USER DBTAP01;


grant CREATE DBT PROJECT on schema sys_dbt.yk to role rl_dbt_func_rw with grant option;
grant usage on schema sys_dbt.yk to role rl_dbt_func_rw with grant option;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_func_rw WITH GRANT OPTION;

grant role sysadmin to role rl_dbt_func_rw;
GRANT ROLE rl_dbt_func_rw TO ROLE rl_dbt_user;
GRANT ROLE rl_dbt_user TO USER H2640;
GRANT ROLE rl_dbt_user TO USER H2122;
GRANT ROLE rl_dbt_user TO USER HI036;
GRANT ROLE rl_dbt_user TO USER HI040;
GRANT ROLE rl_dbt_user TO USER AFWAP03;

SHOW grants to user HI036;

GRANT USAGE, CREATE SCHEMA, MODIFY ON DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;

GRANT USAGE ON DATABASE SYS_DBT TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT USAGE ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_user WITH GRANT OPTION;
GRANT CREATE DBT PROJECT ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_user WITH GRANT OPTION;
--grant:o // execute:x
GRANT ALL PRIVILEGES ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_user WITH GRANT OPTION;
SHOW SCHEMAS LIKE 'YK' IN DATABASE SYS_DBT;

-- GRANT USAGE ON DATABASE SYS_DBT          TO ROLE rl_dbt_func_rw;
-- GRANT USAGE ON SCHEMA SYS_DBT.YK         TO ROLE rl_dbt_func_rw;

-- GRANT CREATE TABLE       ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;
-- GRANT CREATE VIEW        ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;
-- GRANT CREATE STAGE       ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;
-- GRANT CREATE FILE FORMAT ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;
-- GRANT CREATE FUNCTION    ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;
-- GRANT CREATE PROCEDURE ON SCHEMA SYS_DBT.YK TO ROLE rl_dbt_func_rw;


grant ownership on DWDM.CRM.IFPD_CROSS_PROD_RCMN_M to role sysadmin revoke current grants;
show grants on table DWDM.CRM.IFPD_CROSS_PROD_RCMN_M;
-- DWDM.CRM.IFPD_CROSS_PROD_RCMN_M
SHOW GRANTS ON TABLE DWDM.CRM.IFPD_CROSS_PROD_RCMN_M;

-- DBT PROJECT 'SYS_DBT.PROJECT.HNT_DP' does not exist or not authorized.
 
-- grant ownership on SYS_DBT.PROJECT.HNT_DP to role sysadmin revoke current grants; --x
grant ownership on SYS_DBT.PROJECT.HNT_DP to role sysadmin; --x
SHOW GRANTS ON DBT PROJECT SYS_DBT.PROJECT.HNT_DP;
