use role useradmin;
-------------------------------------------------------------------------------------------------
CREATE ROLE rl_cdc_user COMMENT = 'CDC user 권한';
-- alter role rl_cdc_user set COMMENT = 'CDC user 권한';

GRANT ROLE sysadmin TO ROLE rl_cdc_user;
GRANT ROLE rl_cdc_user TO USER CDCAP01;
GRANT ROLE rl_cdc_user TO USER HI040;
-------------------------------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE cdc_wh TO ROLE rl_cdc_user;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE rl_cdc_user WITH GRANT OPTION;

GRANT USAGE, CREATE SCHEMA, MODIFY ON DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE CDC TO ROLE rl_cdc_user WITH GRANT OPTION;

GRANT USAGE, CREATE SCHEMA, MODIFY ON DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT USAGE ON ALL SCHEMAS IN DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE STG_CDC TO ROLE rl_cdc_user WITH GRANT OPTION;
