

-------------------------------------------------
-- 1. 데이터 포맷 생성하기
CREATE OR REPLACE FILE FORMAT STG_EXTERNAL.CDC.PARQUET
    TYPE = PARQUET
    COMPRESSION = SNAPPY;


-------------------------------------------------
-- 2. 테이블 스키마 자동으로 만들기
-- 대상 스테이지 경로 '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/LOAD00000001.snappy.parquet'

CREATE OR REPLACE TABLE <TABLE_NAME>
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/LOAD00000001.snappy.parquet',
      FILE_FORMAT=>'STG_EXTERNAL.CDC.PARQUET'
    )
  )
);


-------------------------------------------------
-- 3. COPY 문으로 테이블에 데이터 넣기
-- 대상 스테이지 경로 '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/LOAD00000001.snappy.parquet'

COPY INTO CDC.HUB01.VOC_DMND_EXNS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/'
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CDC.PARQUET')
ON_ERROR='CONTINUE'
PATTERN = '.*\\.parquet$'
FORCE=TRUE;



SELECT * FROM CDC.HUB01.VOC_DMND_EXNS_M;


-------------------------------------------------
-- 4. 외부 테이블 만들기
-- Stage 경로 - '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/20251118-060841007.snappy.parquet'

CREATE OR REPLACE EXTERNAL TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/',
        FILES => ('20251118-060841007.snappy.parquet'),
        FILE_FORMAT=>'STG_EXTERNAL.CDC.PARQUET'
      )
    )
  )
  LOCATION= @"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/
  FILE_FORMAT= (TYPE = PARQUET)
  AUTO_REFRESH=true
  PATTERN = '.*\\.parquet$'
;

SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct;

SELECT * FROM STG_EXTERNAL.INFORMATION_SCHEMA.TABLES;
DESC EXTERNAL TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct;

-------------------------------------------------
-- 5. Stream 에 이벤트 올리기 (EXTERNAL_TABLE)

ALTER EXTERNAL TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct REFRESH;


CREATE OR REPLACE STREAM STG_EXTERNAL.CDC.STREAM_VOC_DMND_EXNS_M_ct
    ON EXTERNAL TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct
    AT (OFFSET => -7200)
    INSERT_ONLY = TRUE
;


SELECT * FROM STG_EXTERNAL.CDC.STREAM_VOC_DMND_EXNS_M_ct;


SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct;

ls '@STG_EXTERNAL.CDC.NEON';


--------------------------------------------------------------------------
---- 6. Stream 에 이벤트 올리기 (TABLE)

CREATE OR REPLACE TABLE STG_EXTERNAL.CDC.TABLE_VOC_DMND_EXNS_M_ct AS 
 SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct;


CREATE OR REPLACE STREAM STG_EXTERNAL.CDC.STREAM2_VOC_DMND_EXNS_M_ct
    ON TABLE STG_EXTERNAL.CDC.TABLE_VOC_DMND_EXNS_M_ct 
    SHOW_INITIAL_ROWS = TRUE 
;


SELECT * FROM STG_EXTERNAL.CDC.STREAM2_VOC_DMND_EXNS_M_ct;



