
-- Target Table
--- STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_TEST

-------------------------------------------------
-- 1. 테이블 스키마 자동으로 만들기
-- 대상 스테이지 경로 '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/LOAD00000001.snappy.parquet'

CREATE OR REPLACE TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/20251118-060841007.snappy.parquet',
      FILE_FORMAT=>'STG_EXTERNAL.CDC.PARQUET'
    )
  )
);


-------------------------------------------------
-- 2. SNOWPIPE + COPY 문으로 테이블에 데이터 넣기
-- Stage 경로 - '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/20251118-060841007.snappy.parquet'
CREATE OR REPLACE PIPE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_snowpipe
  AUTO_INGEST = TRUE
AS
COPY INTO STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/'
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CDC.PARQUET')
ON_ERROR='CONTINUE'
PATTERN = '.*\\.parquet$'
;

DESCRIBE PIPE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_snowpipe;


-------------------------------------------------
-- 3. Snowpipe Refresh
ALTER PIPE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_snowpipe REFRESH;


SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST;


-- 변경분 필드
  -- "hd_change_oper": "U",
  -- "hd_change_seq": "20251118060733000000000000000120953",
  -- "hd_timestamp": "2025-11-18 06:07:33.000"

SELECT $1
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M_ct/20251118-060841007.snappy.parquet'
(FILE_FORMAT => 'STG_EXTERNAL.CDC.PARQUET')
;



--------------------------------------------------------------------------
---- 3. Stream 에 이벤트 올리기 (TABLE)

-- CREATE OR REPLACE STREAM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_stream
--     ON TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST 
--     SHOW_INITIAL_ROWS = TRUE 
--     -- APPEND_ONLY = TRUE
-- ;

-- SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_stream;



--------------------------------------------------------------------------
---- 4. DYNAMIC TABLE 에 변경분 업데이트 (TABLE)

-- 실제 로우
---- 2500372975	100098929	100098930	100098935	100098973																			S			2025-11-16 16:20:04.000		C209518273	CHPC0MPG0201M100	2025-11-16 16:20:04.000	C209518273	CHPC0MPG0201M100	2025-11-17 15:45:22.000



-- 변경 대상
---- 20251118025450000000000000000104341	U	2025-11-18 02:54:50.000	2500372975	100098929	100098930	100098935	100098973								29V3	HI151	신호준B			F						S			2025-11-16 16:20:04.000		C209518273	CHPC0MPG0201M100	2025-11-18 11:54:50.000	HI151	WPT0000050022	2025-11-18 11:54:58.000

---- 20251118025946000000000000000104661	I	2025-11-18 02:59:46.000	2500373854	100098929	100098930	100098934	100098970																			S			2025-11-18 11:59:46.000		C209807719	CHPC0CUC0002M200	2025-11-18 11:59:46.000	C209807719	CHPC0CUC0002M200	2025-11-18 11:59:53.000

SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_TEST
WHERE RCPN_NUM = '2500372975';



CREATE OR REPLACE DYNAMIC TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_dynamic
TARGET_LAG = '10 MINUTES'
WAREHOUSE = DYNAMIC_WH
AS 

WITH CDC_TABLE AS(
    SELECT T2.* 
    -- EXCLUDE ("hd_change_seq","hd_change_oper", "hd_timestamp", RNUM)
    FROM ( 
        SELECT T1.*,
                ROW_NUMBER() OVER(PARTITION BY T1.RCPN_NUM ORDER BY "hd_change_seq" DESC) AS RNUM
        FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST T1
        ) T2
    WHERE T2.RNUM = 1
)
SELECT * FROM CDC_TABLE
;


MERGE INTO STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_TEST AS TARGET
USING(
    SELECT *
    FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_dynamic
) AS CDC_SOURCE

ON TARGET.RCPN_NUM = CDC_SOURCE.RCPN_NUM

WHEN MATCHED AND CDC_SOURCE."hd_change_oper" = 'U' THEN
    UPDATE SET 
        TARGET.RCPN_NUM = CDC_SOURCE.RCPN_NUM,
        TARGET.VOC_DMND_TYPE_CD1 = CDC_SOURCE.VOC_DMND_TYPE_CD1,
        TARGET.VOC_DMND_TYPE_CD2 = CDC_SOURCE.VOC_DMND_TYPE_CD2,
        TARGET.VOC_DMND_TYPE_CD3 = CDC_SOURCE.VOC_DMND_TYPE_CD3,
        TARGET.VOC_DMND_TYPE_CD4 = CDC_SOURCE.VOC_DMND_TYPE_CD4,
        TARGET.VOC_DMND_TYPE_CD5 = CDC_SOURCE.VOC_DMND_TYPE_CD5,
        TARGET.CATG_SSC_TYPE_CD = CDC_SOURCE.CATG_SSC_TYPE_CD,
        TARGET.VOC_DMND_RCPN_REFN_CD_CONT = CDC_SOURCE.VOC_DMND_RCPN_REFN_CD_CONT,
        TARGET.VOC_DMND_RCPN_REFN_NM = CDC_SOURCE.VOC_DMND_RCPN_REFN_NM,
        TARGET.VOC_DMND_RCPN_REFN_CMNT_MEMO = CDC_SOURCE.VOC_DMND_RCPN_REFN_CMNT_MEMO,
        TARGET.KPI_SCP_CD = CDC_SOURCE.KPI_SCP_CD,
        TARGET.VIST_DT = CDC_SOURCE.VIST_DT,
        TARGET.RPPR_DEPT_CD = CDC_SOURCE.RPPR_DEPT_CD,
        TARGET.RPPR_EMPN = CDC_SOURCE.RPPR_EMPN,
        TARGET.RPPR_NM = CDC_SOURCE.RPPR_NM,
        TARGET.OPPB_YN = CDC_SOURCE.OPPB_YN,
        TARGET.AGE_DV_CD = CDC_SOURCE.AGE_DV_CD,
        TARGET.SMS_BLCKF_STAT_CD = CDC_SOURCE.SMS_BLCKF_STAT_CD,
        TARGET.VOC_RCPN_BRWS_CNT = CDC_SOURCE.VOC_RCPN_BRWS_CNT,
        TARGET.CMPN_YN = CDC_SOURCE.CMPN_YN,
        TARGET.DPLT_RCPN_YN = CDC_SOURCE.DPLT_RCPN_YN,
        TARGET.ARR_YN = CDC_SOURCE.ARR_YN,
        TARGET.TP_CNSL_YN = CDC_SOURCE.TP_CNSL_YN,
        TARGET.ANSR_RCMS_TYPE_CD = CDC_SOURCE.ANSR_RCMS_TYPE_CD,
        TARGET.VOC_PROS_STG_INFM_CD = CDC_SOURCE.VOC_PROS_STG_INFM_CD,
        TARGET.SEND_YN = CDC_SOURCE.SEND_YN,
        TARGET.INP_DTTM = CDC_SOURCE.INP_DTTM,
        TARGET.VOC_OCRN_CITY_CD = CDC_SOURCE.VOC_OCRN_CITY_CD,
        TARGET.INPR_ID = CDC_SOURCE.INPR_ID,
        TARGET.INP_PRGM_ID = CDC_SOURCE.INP_PRGM_ID,
        TARGET.UPD_DTTM = CDC_SOURCE.UPD_DTTM,
        TARGET.UPDR_ID = CDC_SOURCE.UPDR_ID,
        TARGET.UPD_PRGM_ID = CDC_SOURCE.UPD_PRGM_ID,
        TARGET.CDC_LD_DTTM = CDC_SOURCE.CDC_LD_DTTM

WHEN MATCHED AND CDC_SOURCE."hd_change_oper" = 'D' THEN
    DELETE

WHEN NOT MATCHED AND CDC_SOURCE."hd_change_oper" = 'I' THEN
    INSERT (
        TARGET.RCPN_NUM, 
        TARGET.VOC_DMND_TYPE_CD1, 
        TARGET.VOC_DMND_TYPE_CD2, 
        TARGET.VOC_DMND_TYPE_CD3, 
        TARGET.VOC_DMND_TYPE_CD4, 
        TARGET.VOC_DMND_TYPE_CD5, 
        TARGET.CATG_SSC_TYPE_CD, 
        TARGET.VOC_DMND_RCPN_REFN_CD_CONT, 
        TARGET.VOC_DMND_RCPN_REFN_NM, 
        TARGET.VOC_DMND_RCPN_REFN_CMNT_MEMO, 
        TARGET.KPI_SCP_CD, 
        TARGET.VIST_DT, 
        TARGET.RPPR_DEPT_CD, 
        TARGET.RPPR_EMPN, 
        TARGET.RPPR_NM, 
        TARGET.OPPB_YN, 
        TARGET.AGE_DV_CD, 
        TARGET.SMS_BLCKF_STAT_CD, 
        TARGET.VOC_RCPN_BRWS_CNT, 
        TARGET.CMPN_YN, 
        TARGET.DPLT_RCPN_YN, 
        TARGET.ARR_YN, 
        TARGET.TP_CNSL_YN, 
        TARGET.ANSR_RCMS_TYPE_CD, 
        TARGET.VOC_PROS_STG_INFM_CD, 
        TARGET.SEND_YN, 
        TARGET.INP_DTTM, 
        TARGET.VOC_OCRN_CITY_CD, 
        TARGET.INPR_ID, 
        TARGET.INP_PRGM_ID, 
        TARGET.UPD_DTTM, 
        TARGET.UPDR_ID,
        TARGET.UPD_PRGM_ID, 
        TARGET.CDC_LD_DTTM
    )
    VALUES(
        CDC_SOURCE.RCPN_NUM, 
        CDC_SOURCE.VOC_DMND_TYPE_CD1, 
        CDC_SOURCE.VOC_DMND_TYPE_CD2, 
        CDC_SOURCE.VOC_DMND_TYPE_CD3, 
        CDC_SOURCE.VOC_DMND_TYPE_CD4, 
        CDC_SOURCE.VOC_DMND_TYPE_CD5, 
        CDC_SOURCE.CATG_SSC_TYPE_CD, 
        CDC_SOURCE.VOC_DMND_RCPN_REFN_CD_CONT, 
        CDC_SOURCE.VOC_DMND_RCPN_REFN_NM, 
        CDC_SOURCE.VOC_DMND_RCPN_REFN_CMNT_MEMO, 
        CDC_SOURCE.KPI_SCP_CD, 
        CDC_SOURCE.VIST_DT, 
        CDC_SOURCE.RPPR_DEPT_CD, 
        CDC_SOURCE.RPPR_EMPN, 
        CDC_SOURCE.RPPR_NM, 
        CDC_SOURCE.OPPB_YN, 
        CDC_SOURCE.AGE_DV_CD, 
        CDC_SOURCE.SMS_BLCKF_STAT_CD, 
        CDC_SOURCE.VOC_RCPN_BRWS_CNT, 
        CDC_SOURCE.CMPN_YN, 
        CDC_SOURCE.DPLT_RCPN_YN, 
        CDC_SOURCE.ARR_YN, 
        CDC_SOURCE.TP_CNSL_YN, 
        CDC_SOURCE.ANSR_RCMS_TYPE_CD, 
        CDC_SOURCE.VOC_PROS_STG_INFM_CD, 
        CDC_SOURCE.SEND_YN, 
        CDC_SOURCE.INP_DTTM, 
        CDC_SOURCE.VOC_OCRN_CITY_CD, 
        CDC_SOURCE.INPR_ID, 
        CDC_SOURCE.INP_PRGM_ID, 
        CDC_SOURCE.UPD_DTTM, 
        CDC_SOURCE.UPDR_ID,
        CDC_SOURCE.UPD_PRGM_ID, 
        CDC_SOURCE.CDC_LD_DTTM
    )
;

SELECT * FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_dynamic
WHERE RCPN_NUM ='2500373934';


SELECT * EXCLUDE ("hd_change_seq", "hd_change_oper", "hd_timestamp")
FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST;



SELECT * 
FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_ct_TEST
WHERE RCPN_NUM = '2500372975';

SELECT * 
FROM STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_TEST
WHERE RCPN_NUM = '2500372975';


--
DESCRIBE TABLE STG_EXTERNAL.CDC.VOC_DMND_EXNS_M_CT_TEST;



---- hd_change_seq,
---- hd_change_oper,
---- hd_timestamp,
-- RCPN_NUM,
-- VOC_DMND_TYPE_CD1,
-- VOC_DMND_TYPE_CD2,
-- VOC_DMND_TYPE_CD3,
-- VOC_DMND_TYPE_CD4,
-- VOC_DMND_TYPE_CD5,
-- CATG_SSC_TYPE_CD,
-- VOC_DMND_RCPN_REFN_CD_CONT,
-- VOC_DMND_RCPN_REFN_NM,
-- VOC_DMND_RCPN_REFN_CMNT_MEMO,
-- KPI_SCP_CD,
-- VIST_DT,
-- RPPR_DEPT_CD,
-- RPPR_EMPN,
-- RPPR_NM,
-- OPPB_YN,
-- AGE_DV_CD,
-- SMS_BLCKF_STAT_CD,
-- VOC_RCPN_BRWS_CNT,
-- CMPN_YN,
-- DPLT_RCPN_YN,
-- ARR_YN,
-- TP_CNSL_YN,
-- ANSR_RCMS_TYPE_CD,
-- VOC_PROS_STG_INFM_CD,
-- SEND_YN,
-- INP_DTTM,
-- VOC_OCRN_CITY_CD,
-- INPR_ID,
-- INP_PRGM_ID,
-- UPD_DTTM,
-- UPDR_ID,
-- UPD_PRGM_ID,
-- CDC_LD_DTTM


