DESC TABLE STG_CDC.CST01.CST_DL_CUST_M;



--HTL_CD,HTL_KO_NM,HTL_EN_NM,HTL_APLC_LANG_NM,SRCH_HTL_NM,LDG_TYPE_CD,BLNG_CHAN_CD,BRND_CD,TEL_VAL,FAXN_VAL,ROOM_GRP_YN,ROOM_CATG_NM,CNTRY_CD,CITY_CD,XPEDIA_CITY_CD,AREA_CD,EN_ADRS,APLC_LANG_ADRS,LA,LO,CMS_HTL_CD,USE_YN,XPEDIA_HTL_CD,HTL_BRND_ICLT_CD,ROUT_CD,LDG_GRAD_CD,ETL_RGST_DTTM,ETL_UPD_DTTM,CHD_BASS_USE_YN,CHD_MAX_AGE,GG_CD

DESC TABLE DWDM.INF01.IBCO_HTL_C;

select $1 FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_RSPB_AGT_STAF_D/LOAD00000001.snappy.parquet'
(FILE_FORMAT => 'STG_EXTERNAL.CDC.PARQUET');



create or replace pipe STG_CDC.STT01.DEP_CARD_AUTH_D 
 auto_ingest=true as 
COPY INTO STG_CDC.STT01.DEP_CARD_AUTH_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_CARD_AUTH_D/'
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\.parquet$'
ON_ERROR = 'CONTINUE';
--ON_ERROR = 'SKIP_FILE';

execute task STG_CDC.STT01.DEP_CARD_AUTH_D;

COPY INTO STG_CDC.STT01.DEP_CARD_AUTH_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_CARD_AUTH_D/'
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\.parquet$'
ON_ERROR = 'CONTINUE';



SHOW PIPES STG_CDC.STT01.DEP_CARD_AUTH_D;