-- Dossier/Document/Report 사용자별 조회 건수
WITH COUNT_STATS AS 
(
	SELECT TO_CHAR(T_DCMT_STAT.REQUESTRECTIME,'YYYYMM') AS YYYYMM,	
 			TO_CHAR(T_DCMT_STAT.REQUESTRECTIME,'YYYYMMDD') AS YYYYMMDD,
 			T_DCMT_STAT.REQUESTRECTIME as TIME_STAMP,
			'다큐먼트/도씨에' AS D_R_GUBUN,	
			T_DCMT.OBJECT_ID AS REPORT_ID,
			T_DCMT.OBJECT_NAME AS REPORT_NAME,
			T_USR.OBJECT_NAME AS USER_ID,
			COUNT(*) AS CNT
	FROM DWDM.MSS01.STG_IS_DOCUMENT_STATS T_DCMT_STAT,	
		DWDM.MSS01.DSSMDOBJINFO T_USR,	
		DWDM.MSS01.DSSMDOBJINFO T_DCMT
	WHERE  1=1 
		AND T_DCMT_STAT.USERID = T_USR.OBJECT_ID
		AND T_DCMT_STAT.DOCUMENTID = T_DCMT.OBJECT_ID
		and T_DCMT_STAT.DOCUMENTID not in ('4802DE4C4C18F434C75BFA84EC8A5E4B', '8154998B41AE3328BBB70692605904E4') -- 웹에서 다큐먼트/도씨에를 새로 생성할 때, 실행되는 빈 템플릿 제외
		AND T_DCMT.PROJECT_ID = '5D4EC826B84B8CC9A7AB07BF60E7D625' -- 프로젝트 ID 교체 필요
	GROUP BY TO_CHAR(T_DCMT_STAT.REQUESTRECTIME,'YYYYMM'),	
			TO_CHAR(T_DCMT_STAT.REQUESTRECTIME,'YYYYMMDD'),
			T_DCMT_STAT.REQUESTRECTIME,
			T_DCMT.OBJECT_ID,	
			T_DCMT.OBJECT_NAME,
			T_USR.OBJECT_NAME
	UNION ALL
	SELECT TO_CHAR(T_REP_STAT.REQUESTRECTIME,'YYYYMM') YYYYMM,	
			TO_CHAR(T_REP_STAT.REQUESTRECTIME,'YYYYMMDD') YYYYMMDD,
			T_REP_STAT.REQUESTRECTIME TIME_STAMP,
			'리포트' AS D_R_GUBUN,
			T_RPT.OBJECT_ID   AS REPORT_ID, 
			T_RPT.OBJECT_NAME AS REPORT_NAME,
			T_USR.OBJECT_NAME AS USER_ID,
			COUNT(*) as CNT
	FROM DWDM.MSS01.STG_IS_REPORT_STATS T_REP_STAT,	
		DWDM.MSS01.DSSMDOBJINFO T_USR,	
		DWDM.MSS01.DSSMDOBJINFO T_RPT
	WHERE  1=1 
		AND T_REP_STAT.USERID = T_USR.OBJECT_ID
		AND T_REP_STAT.REPORTID = T_RPT.OBJECT_ID
		and T_REP_STAT.REPORTID != '05B202B9999F4C1AB960DA6208CADF3D' -- 웹에서 리포트를 새로 생성할 때, 실행되는 빈 템플릿 제외
		AND T_RPT.PROJECT_ID = '5D4EC826B84B8CC9A7AB07BF60E7D625' -- 프로젝트 ID 교체 필요
		AND T_REP_STAT.PARENTINDICATOR != 1 -- 도씨에/다큐먼트 실행 시 실행된 리포트 건 수 제외
	GROUP BY TO_CHAR(T_REP_STAT.REQUESTRECTIME,'YYYYMM'),	
			TO_CHAR(T_REP_STAT.REQUESTRECTIME,'YYYYMMDD'),
			T_REP_STAT.REQUESTRECTIME,
			T_RPT.OBJECT_ID,
			T_RPT.OBJECT_NAME,
			T_USR.OBJECT_NAME
)
/** ==================================== **/
SELECT DISTINCT 
		YYYYMM AS "실행년월",
		YYYYMMDD AS "실행일자",
		TIME_STAMP AS "실행 시각",
		REPORT_NAME AS "보고서 명",
		REPORT_ID AS "보고서 ID",
		D_R_GUBUN AS "보고서 타입",
		USER_ID AS "사용자 명",
		SUM(CNT) AS "보고서 실행 수" -- 리포트, 도씨에, 다큐먼트 모두 포함한 보고서 실행 건수 (도씨에/다큐먼트 실행 시 실행된 리포트 건 수는 제외 됨)
FROM COUNT_STATS
where 1=1 
GROUP BY YYYYMM, YYYYMMDD, USER_ID, REPORT_NAME, TIME_STAMP, REPORT_ID, D_R_GUBUN
ORDER BY YYYYMM DESC, YYYYMMDD DESC, TIME_STAMP DESC
;

select *
from DWDM.m
