WITH TEMP1(OBJECT_ID,
OBJECT_NAME,
PARENT_ID,
F_PATH,
LVL,
OBJECT_TYPE) AS (
SELECT
	OBJECT_ID,
	OBJECT_NAME,
	PARENT_ID,
	OBJECT_NAME AS F_PATH,
	1 AS LVL,
	OBJECT_TYPE
FROM
	DWDM.MSS01.DSSMDOBJINFO
WHERE
	1 = 1
/* 디벨로퍼 접속 > 좌측 메뉴 중, 프로젝트 명칭 우클릭 > 프로젝트 구성 > ID 확인 > 아래 ID 교체 필요 */
	AND PROJECT_ID = '5D4EC826B84B8CC9A7AB07BF60E7D625'
UNION ALL
SELECT
	E.OBJECT_ID,
	E.OBJECT_NAME,
	E.PARENT_ID,
	T.F_PATH || '/' || E.OBJECT_NAME AS F_PATH,
	T.LVL + 1 AS LVL,
	E.OBJECT_TYPE
FROM
	TEMP1 T
JOIN DWDM.MSS01.DSSMDOBJINFO E ON
	(T.OBJECT_ID = E.PARENT_ID)
WHERE
	1 = 1
/* 디벨로퍼 접속 > 좌측 메뉴 중, 프로젝트 명칭 우클릭 > 프로젝트 구성 > ID 확인 > 아래 ID 교체 필요 */
	AND E.PROJECT_ID = '5D4EC826B84B8CC9A7AB07BF60E7D625'
)
/* =====================================*/
/* =====================================*/
/* 최종 전체 개체 경로 파악 용 임시 테이블 */
/* =====================================*/
,
REP_PATH_T AS (
SELECT
	OBJECT_ID,
	OBJECT_NAME,
	PARENT_ID,
	F_PATH,
	RANK() OVER (PARTITION BY OBJECT_ID
ORDER BY
	LVL DESC) AS PATH_RANK,
	OBJECT_TYPE
FROM
	TEMP1
)
/* =====================================*/
/* =====================================*/
/* 종속 관계 개체 파악 용 임시 테이블 */
/* =====================================*/
,
DEP_OBJ AS (
SELECT
	DEP.OBJECT_ID,
	DEP.DEPN_OBJID,
	D.OBJECT_NAME,
	D.OBJECT_TYPE
FROM
	DWDM.MSS01.DSSMDOBJINFO D
JOIN TEMP1 T ON
	(D.OBJECT_ID = T.OBJECT_ID)
INNER JOIN DWDM.MSS01.DSSMDOBJDEPN DEP ON
	(DEP.DEPN_OBJID = D.OBJECT_ID)
)
,
TAB_TB AS (
SELECT
	DISTINCT DEP.DEPN_OBJID AS "TAB_ID",
	DEP.OBJECT_NAME AS "TAB_NAME",
	D.OBJECT_ID AS "ATT_ID",
	D.OBJECT_NAME AS "ATT_NAME"
FROM
	DWDM.MSS01.DSSMDOBJINFO D
JOIN DEP_OBJ DEP ON
	(D.OBJECT_ID = DEP.OBJECT_ID)
JOIN REP_PATH_T RPATH ON
	(D.OBJECT_ID = RPATH.OBJECT_ID)
WHERE
	1 = 1
	AND DEP.DEPN_OBJID IN (
	SELECT
		OBJECT_ID
	FROM
		DWDM.MSS01.DSSMDOBJINFO
	WHERE 1 = 1
		AND DEP.OBJECT_TYPE IN ('15') -- TABLE OBJECT TYPE
)
		AND D.OBJECT_TYPE IN ('12', '13') -- ATTRIBUTE , FACT OBJECT TYPE
			AND RPATH.PATH_RANK = '1'
)
/* =====================================*/
SELECT
	DISTINCT T.TAB_ID AS "TABLE ID",
	T.TAB_NAME AS "TABLE NAME",
	T.ATT_ID AS "ATTRIBUTE/FACT ID",
	T.ATT_NAME AS "ATTRIBUTE/FACT NAME",
	D.OBJECT_ID AS "종속 개체 ID",
	D.OBJECT_NAME AS "종속 개체 명",
	CASE WHEN D.OBJECT_TYPE = '3' THEN '그리드/큐브'
		WHEN D.OBJECT_TYPE = '55' THEN '도씨에/다큐먼트'
		WHEN D.OBJECT_TYPE = '1' THEN '필터'
	END AS "종속 개체 TYPE",
	RPATH.F_PATH AS "PATH"
FROM
	DWDM.MSS01.DSSMDOBJINFO D
JOIN DEP_OBJ DEP ON
	(D.OBJECT_ID = DEP.OBJECT_ID)
JOIN TAB_TB T ON
	(DEP.DEPN_OBJID = T.ATT_ID)
JOIN REP_PATH_T RPATH ON
	(D.OBJECT_ID = RPATH.OBJECT_ID)
WHERE
	1 = 1
	AND RPATH.PATH_RANK = '1'    
	-- 최종 경로만 추출하는 조건으로 변경 금지
	AND D.OBJECT_TYPE IN ('3', '55', '1')
	-- 그리드 보고서 및 큐브, 도씨에 및 다큐먼트만 추출하는 조건
;