
use database cdc;
use warehouse cdc_wh;

/*
    이상한 값으로 인해 copy into 안됨
    
    DCD_AIR_PAY_DTRB_X
    DCD_AIR_CUPN_PAY_X
*/


SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('AIR01')
and table_name not in ('DCD_AIR_PAY_DTRB_X','DCD_AIR_CUPN_PAY_X');



show tasks;

CALL CDC.PUBLIC.CDC_INITIAL_LOAD_SCRIPT('CDC.CST01.CST_MEM_AMITY_AGT_D');
CALL CDC.PUBLIC.CDC_CREATE_PIPE_SCRIPT('CDC.CST01.CST_MEM_AMITY_AGT_D');
CALL CDC.PUBLIC.CDC_CREATE_MERGE_PROC_SCRIPT('CDC.CST01.CST_MEM_AMITY_AGT_D');
CALL CDC.PUBLIC.CDC_CREATE_TASK_SCRIPT('CDC.CST01.CST_MEM_AMITY_AGT_D');



execute task CDC.PUBLIC.AIR01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'AIR01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


-- Uncaught exception of type 'STATEMENT_ERROR' on line 13 at position 0 : Invalid UTF8 detected while decoding '�����0xED0xBF0xA9_�ϳ�_2����'
;

CREATE OR REPLACE TASK CDC.PUBLIC.AIR01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN

COPY INTO CDC.AIR01.COM_AIR_VI_EVENT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_VI_EVENT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_CUPN_PAY_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_CUPN_PAY_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_INSR_JOIN_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_INSR_JOIN_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_SRC_PNR_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_SRC_PNR_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_RFD_AMT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_RFD_AMT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_DT_PER_SBS_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_DT_PER_SBS_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_CONJ_TKT_LST_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_CONJ_TKT_LST_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_PATR_ITNR_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_PATR_ITNR_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_SPLY_SEAT_UPD_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_SPLY_SEAT_UPD_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_ISUE_REQ_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_ISUE_REQ_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_VOID_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_VOID_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_ONLN_CNSL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_ONLN_CNSL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_EVENT_EXLS_TKT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_EVENT_EXLS_TKT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_RFD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_RFD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_RES_ITNR_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_RES_ITNR_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_RES_STAT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_RES_STAT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_CLAS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_CLAS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_MGR_RGST_AA_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_MGR_RGST_AA_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_FEE_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_FEE_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_BILG_ACM_ADM_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_BILG_ACM_ADM_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_RES_STAT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_RES_STAT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_VI_AGT_GRP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_VI_AGT_GRP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_RFD_PRGS_STAT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_RFD_PRGS_STAT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_TAXAMT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_TAXAMT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_BILG_CYCL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_BILG_CYCL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_SEAT_CLAS_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_SEAT_CLAS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.PPD_AIR_EVENT_CD_SS_CD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.PPD_AIR_EVENT_CD_SS_CD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_EVENT_TRGT_A_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_EVENT_TRGT_A_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_EXLS_RPPR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_EXLS_RPPR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_SUPL_FEE_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_SUPL_FEE_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_FRST_SLLPRC_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_FRST_SLLPRC_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_UNFY_RES_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_UNFY_RES_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_SPLPRC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_SPLPRC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_RES_AIRSCH_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_RES_AIRSCH_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_DT_PER_SBS_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_DT_PER_SBS_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_EVENT_TRGT_AC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_EVENT_TRGT_AC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_SITE_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_SITE_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_RES_PURC_FIX_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_RES_PURC_FIX_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_PATR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_PATR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_CRS_ISUE_SEG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_CRS_ISUE_SEG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_SPLY_SEAT_DEPO_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_SPLY_SEAT_DEPO_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_AIRL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_AIRL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_EXLS_SLS_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_EXLS_SLS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_BILG_DSR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_BILG_DSR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_PAY_DTRB_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_PAY_DTRB_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_RFD_SETT_AMT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_RFD_SETT_AMT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_BILG_RFD_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_BILG_RFD_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_D_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_SLLPRC_D_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_TASF_DSR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_TASF_DSR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_VI_AGT_GRP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_VI_AGT_GRP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_RFD_TKT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_RFD_TKT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_CLAS_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_CLAS_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_STAT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_STAT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_MLG_COLT_AIRL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_MLG_COLT_AIRL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.COM_AIR_VI_AGT_GRP_CRP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.COM_AIR_VI_AGT_GRP_CRP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_UNFY_RES_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_UNFY_RES_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_SPLY_RPPR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_SPLY_RPPR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_SPLY_SEAT_TL_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_SPLY_SEAT_TL_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_BILG_RFD_T_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_BILG_RFD_T_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.PPD_AIR_EVENT_CD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.PPD_AIR_EVENT_CD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_SLLPRC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_SLLPRC_STAT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_SLLPRC_STAT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_CLAS_ATTR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_CLAS_ATTR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DSR_AIR_DSR_ISUE_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DSR_AIR_DSR_ISUE_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_INSR_TKT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_INSR_TKT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_UNFY_RES_GRP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_UNFY_RES_GRP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.PPD_LWPRC_INFM_REQ_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.PPD_LWPRC_INFM_REQ_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_ADDT_SVC_PURC_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_ADDT_SVC_PURC_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.RSV_AIR_PSNGR_PAY_S_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.RSV_AIR_PSNGR_PAY_S_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.SAC_AIV_SPLY_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.SAC_AIV_SPLY_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;




END;




SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('AIR01') and row_count = 0 and table_name <> 'RSV_AIR_RES_PURC_FIX_M';


CALL CDC.PUBLIC.CDC_GENERATE_COPY_SQL(ARRAY_CONSTRUCT(
'CDC.AIR01.RSV_AIR_RES_PURC_FIX_M',
'CDC.AIR01.COM_AIR_SEAT_CLAS_D',
'CDC.AIR01.DCD_AIR_CUPN_PAY_X',
'CDC.AIR01.DCD_AIR_PAY_DTRB_X',
'CDC.AIR01.DCD_AIR_RFD_SETT_AMT_D',
'CDC.AIR01.DSR_AIR_BILG_RFD_X',
'CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_D_M',
'CDC.AIR01.DSR_AIR_TASF_DSR_M',
'CDC.AIR01.COM_AIR_VI_AGT_GRP_M',
'CDC.AIR01.RSV_AIR_PSNGR_STAT_X',
'CDC.AIR01.COM_AIR_MLG_COLT_AIRL_D',
'CDC.AIR01.COM_AIR_VI_AGT_GRP_CRP_D',
'CDC.AIR01.RSV_AIR_UNFY_RES_M',
'CDC.AIR01.SAC_AIV_SPLY_SEAT_TL_X',
'CDC.AIR01.SAC_AIV_SPLY_RPPR_M',
'CDC.AIR01.DSR_AIR_BILG_RFD_T_X',
'CDC.AIR01.PPD_AIR_EVENT_CD_M',
'CDC.AIR01.RSV_AIR_SLLPRC_STAT_X',
'CDC.AIR01.RSV_INSR_TKT_M',
'CDC.AIR01.SAC_AIV_CLAS_ATTR_M',
'CDC.AIR01.DSR_AIR_DSR_ISUE_X',
'CDC.AIR01.PPD_LWPRC_INFM_REQ_M',
'CDC.AIR01.RSV_AIR_ADDT_SVC_PURC_H',
'CDC.AIR01.RSV_AIR_PSNGR_PAY_S_M',
'CDC.AIR01.SAC_AIV_SPLY_M'
));



select * from CDC.AIR01.DCD_AIR_PAY_DTRB_X;
select * from CDC.AIR01.DCD_AIR_CUPN_PAY_X;


-- 에러발생
-- REPLACE_INVALID_CHARACTERS = TRUE 옵션 추가 사용 시 해소 가능

COPY INTO CDC.AIR01.DCD_AIR_CUPN_PAY_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_CUPN_PAY_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET REPLACE_INVALID_CHARACTERS = TRUE)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.AIR01.DCD_AIR_PAY_DTRB_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/AIR01.DCD_AIR_PAY_DTRB_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET REPLACE_INVALID_CHARACTERS = TRUE)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.AIR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


-- 완료
-- CDC.AIR01.DCD_AIR_RFD_SETT_AMT_D
-- CDC.AIR01.DSR_AIR_BILG_RFD_X
-- CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_D_M
-- CDC.AIR01.DSR_AIR_TASF_DSR_M
-- CDC.AIR01.COM_AIR_VI_AGT_GRP_M
-- CDC.AIR01.RSV_AIR_PSNGR_STAT_X
-- CDC.AIR01.COM_AIR_MLG_COLT_AIRL_D
-- CDC.AIR01.COM_AIR_VI_AGT_GRP_CRP_D
-- CDC.AIR01.RSV_AIR_UNFY_RES_M
-- CDC.AIR01.SAC_AIV_SPLY_SEAT_TL_X
-- CDC.AIR01.SAC_AIV_SPLY_RPPR_M
-- CDC.AIR01.DSR_AIR_BILG_RFD_T_X
-- CDC.AIR01.PPD_AIR_EVENT_CD_M
-- CDC.AIR01.RSV_AIR_SLLPRC_STAT_X
-- CDC.AIR01.RSV_INSR_TKT_M
-- CDC.AIR01.SAC_AIV_CLAS_ATTR_M
-- CDC.AIR01.DSR_AIR_DSR_ISUE_X
-- CDC.AIR01.PPD_LWPRC_INFM_REQ_M
-- CDC.AIR01.RSV_AIR_ADDT_SVC_PURC_H
-- CDC.AIR01.RSV_AIR_PSNGR_PAY_S_M
-- CDC.AIR01.SAC_AIV_SPLY_M






