
use database cdc;
use warehouse cdc_wh;




SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('COM01');






show tasks;

execute task CDC.PUBLIC.COM01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'COM01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;





CREATE OR REPLACE TASK CDC.PUBLIC.COM01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.CHL01.CTS_RSRC_IMG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_RSRC_IMG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_LCM_INFM_REQ_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_LCM_INFM_REQ_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_CATG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_CATG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_ADIF_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_ADIF_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_DAR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_DAR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_PROD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_PROD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_EVENT_APCT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_EVENT_APCT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CDM_CARD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CDM_CARD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_PROD_CATG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_PROD_CATG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_PROD_OPTN_PROD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_PROD_OPTN_PROD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_PROD_GOFC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_PROD_GOFC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_DTCM_SVC_STPL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_DTCM_SVC_STPL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_PROD_GOFC_MTLG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_PROD_GOFC_MTLG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_DTCM_RCMN_PLNN_EXHT_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_DTCM_RCMN_PLNN_EXHT_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_BNR_MGMT_COND_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_BNR_MGMT_COND_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_CUPN_REL_COND_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_CUPN_REL_COND_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_CUPN_MSTR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_CUPN_MSTR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_CUST_CUPN_ISNC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_CUST_CUPN_ISNC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_AFCN_RCMN_PLNN_EXHT_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_AFCN_RCMN_PLNN_EXHT_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CDM_TMPL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CDM_TMPL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_SRWR_MGMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_SRWR_MGMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_CUST_MRCP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_CUST_MRCP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CDM_CARD_CLST_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CDM_CARD_CLST_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_ADIF_IMG_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_ADIF_IMG_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_BNR_MGMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_BNR_MGMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_FLTR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_FLTR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_AREA_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_AREA_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_CITY_CATG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_CITY_CATG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COM_SHCR_INFO_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COM_SHCR_INFO_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_CATG_MTLG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_CATG_MTLG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_INFO_FLTR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_INFO_FLTR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_PROD_LDG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_PROD_LDG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_EVENT_INFO_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_EVENT_INFO_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_MTLG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_MTLG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CDM_CARD_GRP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CDM_CARD_GRP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.COT_FAQ_INFO_MGMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.COT_FAQ_INFO_MGMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_PROD_GRP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_PROD_GRP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_CNTNT_GPS_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_CNTNT_GPS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.MPS_DAR_CATG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.MPS_DAR_CATG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_AGT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_AGT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CDM_CARD_GRP_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CDM_CARD_GRP_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.CTS_LCM_BRD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.CTS_LCM_BRD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.CHL01.PDP_PLNN_EXHT_INFO_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/CHL01.PDP_PLNN_EXHT_INFO_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CHL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
