use database cdc;
use warehouse compute_wh;


show tasks;

execute task CDC.PUBLIC.CST01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'CST01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;



CREATE OR REPLACE TASK CDC.PUBLIC.CST01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN

COPY INTO CDC.CST01.CST_NNMM_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_NNMM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_UPD_H
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_UPD_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_JNNG_X
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_JNNG_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_INAT_MEM_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_INAT_MEM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_INAT_MEM_LGN_D
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_INAT_MEM_LGN_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_CNCR_AITM_D
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_CNCR_AITM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_ADRS_D
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_ADRS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_DL_CUST_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_DL_CUST_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_PTNS_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_PTNS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_AGRT_X
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_AGRT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_SCSN_MEM_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_SCSN_MEM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_UPD_REQ_X
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_UPD_REQ_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_MEM_STAF_FAML_R
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_STAF_FAML_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;


COPY INTO CDC.CST01.CST_MEM_GRAD_D
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_MEM_GRAD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

COPY INTO CDC.CST01.CST_DSTRY_CUST_M
FROM '@\"STG_EXTERNAL\".\"CDC\".\"NEON\"/CST01.CST_DSTRY_CUST_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.CST01.PARQUET')
PATTERN = '.*\\.parquet$'
FORCE = TRUE
;

END;