
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HGSIN01');


show tasks;

execute task CDC.PUBLIC.HGSIN01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HGSIN01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HGSIN01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HGSIN01.PUB_AREA
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.PUB_AREA/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_LANDJOIN_DET
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_LANDJOIN_DET/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_PKG_RES
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_PKG_RES/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_HTL_RES_CFM
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_HTL_RES_CFM/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_PKG_GOODS
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_PKG_GOODS/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.GUIDE_POOL_DET
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.GUIDE_POOL_DET/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.DSR_MASTER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.DSR_MASTER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.AGT_AGENT
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.AGT_AGENT/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.OL_ESTI_FILE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.OL_ESTI_FILE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.AGT_MEMBER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.AGT_MEMBER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_INDIVI_GOODS
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_INDIVI_GOODS/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.NG_COMP_MGR
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.NG_COMP_MGR/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.PUB_CITY
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.PUB_CITY/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.DAT_LDG_CITEM
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.DAT_LDG_CITEM/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_HTL_RES
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_HTL_RES/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.PUB_COUNTRY
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.PUB_COUNTRY/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_SALES_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_SALES_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_ETC_RES
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_ETC_RES/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.CDE_HOTEL_CHAIN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.CDE_HOTEL_CHAIN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_INDIVI_RES
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_INDIVI_RES/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HGSIN01.COM_LAND
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HGSIN01.COM_LAND/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HGSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
