
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HTL01');



show tasks;

execute task CDC.PUBLIC.HTL01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HTL01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HTL01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HTL01.COM_HTL_ROOM_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_ROOM_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_SUPL_BASS_MGMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_SUPL_BASS_MGMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_LBL_MGMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_LBL_MGMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SUPL_HTL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SUPL_HTL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_FARE_GRP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_FARE_GRP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_SLPRC_RVNS_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_SLPRC_RVNS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_SPCL_PROM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_SPCL_PROM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_INV_BLK_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_INV_BLK_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_EAN_LDMK_GTHR_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_EAN_LDMK_GTHR_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_HASHTAG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_HASHTAG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_PROM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_PROM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_LDMK_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_LDMK_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_CM_NMKUP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_CM_NMKUP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_EAN_CITY_GTHR_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_EAN_CITY_GTHR_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_FARE_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_FARE_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_LDGR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_LDGR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_MKUP_CHNL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_MKUP_CHNL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_SUPL_VI_CMTN_BASS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_SUPL_VI_CMTN_BASS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_ADD_FARE_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_ADD_FARE_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SPLY_HTL_RPPR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SPLY_HTL_RPPR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_CRPN_SPLY_HTL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_CRPN_SPLY_HTL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_DC_CHNL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_DC_CHNL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_SUPL_VI_AREA_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_SUPL_VI_AREA_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_CUPN_USE_DESC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_CUPN_USE_DESC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_PROM_RTP_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_PROM_RTP_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_BSC_NMKUP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_BSC_NMKUP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_ROOM_RES_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_ROOM_RES_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_ROOM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_ROOM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_RTP_BNFT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_RTP_BNFT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_CM_SLPRC_RVNS_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_CM_SLPRC_RVNS_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_EAN_REVIEW_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_EAN_REVIEW_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SUPL_CITY_MAPP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SUPL_CITY_MAPP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_CHNL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_CHNL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_CHNL_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_CHNL_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SUPL_HTL_MAPP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SUPL_HTL_MAPP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SPLY_HTL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SPLY_HTL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SALE_PROM_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SALE_PROM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_TRPADV_HTL_MAPP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_TRPADV_HTL_MAPP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_DC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_DC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_ORDR_INFO_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_ORDR_INFO_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_RTP_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_RTP_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_CM_INV_BLK_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_CM_INV_BLK_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_DPURC_PKG_RES_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_DPURC_PKG_RES_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_CMPLN_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_CMPLN_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_CRPN_SLPRC_RVNS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_CRPN_SLPRC_RVNS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_CITY_LDMK_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_CITY_LDMK_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_XPEDIA_I
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_XPEDIA_I/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_CNTRY_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_CNTRY_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_EAN_BAS_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_EAN_BAS_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_UPD_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_UPD_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_ADD_FARE_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_ADD_FARE_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_ROOM_RTP_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_ROOM_RTP_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_RTP_ADD_FARE_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_RTP_ADD_FARE_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_SUPL_HTL_SRC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_SUPL_HTL_SRC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_L
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_L/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_NMKUP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_NMKUP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_SLCO_VI_CMTN_BASS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_SLCO_VI_CMTN_BASS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_SUPL_BASS_MGMT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_SUPL_BASS_MGMT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_RES_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_RES_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.RSV_HTL_AFCN_ORDR_INFO_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.RSV_HTL_AFCN_ORDR_INFO_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_SLCO_VI_GOAL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_SLCO_VI_GOAL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_MKUP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_MKUP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SALE_PROM_GOAL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SALE_PROM_GOAL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SLPRC_TYPE_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SLPRC_TYPE_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_CHAN_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_CHAN_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_PROM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_PROM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_CNTRY_ROUT_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_CNTRY_ROUT_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_RTP_CHNL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_RTP_CHNL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_XPEDIA_MAPP_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_XPEDIA_MAPP_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_INV_FARE_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_INV_FARE_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_CHNL_FER_BASS_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_CHNL_FER_BASS_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SAC_HTL_RTP_DESC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SAC_HTL_RTP_DESC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_SUPL_VI_GOAL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_SUPL_VI_GOAL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.SLP_HTL_SVLM_S
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.SLP_HTL_SVLM_S/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTL01.COM_HTL_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTL01.COM_HTL_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTL01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
