
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HTSBR01');


show tasks;

execute task CDC.PUBLIC.HTSBR01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HTSBR01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HTSBR01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HTSBR01.GN_PKG_COACH
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_COACH/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_AIRTEL_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_AIRTEL_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_CDE_CUST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_CDE_CUST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_AIR
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_AIR/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_AGENCY
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_AGENCY/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_OB_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_OB_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.ACC_SLP_DTL
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.ACC_SLP_DTL/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_CONN_MOBILE_LOG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_CONN_MOBILE_LOG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_MISC
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_MISC/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_MAIN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_MAIN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_OB_AIR
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_OB_AIR/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_HOTEL
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_HOTEL/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_OB_PKG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_OB_PKG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.CDE_CTG_SML
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.CDE_CTG_SML/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_ACC_REC
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_ACC_REC/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_CHEQUE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_CHEQUE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_PKG_OB_DET
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_PKG_OB_DET/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_TKT_USE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_TKT_USE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_TKT_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_TKT_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.CDE_MAIDAS_CODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.CDE_MAIDAS_CODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_GRP_PRE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_GRP_PRE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.CDE_CTG_BIG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.CDE_CTG_BIG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_SET_HTL_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_SET_HTL_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.CDE_CTG_MED
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.CDE_CTG_MED/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.CDE_CTG_DET
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.CDE_CTG_DET/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSBR01.GN_PKG_TOUR_FEE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSBR01.GN_PKG_TOUR_FEE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSBR01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
