
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HTSIN01');


show tasks;

execute task CDC.PUBLIC.HTSIN01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HTSIN01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HTSIN01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HTSIN01.EDI2_DOC_CODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.EDI2_DOC_CODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.ITEM_MASTER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.ITEM_MASTER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.COM_DEPT_PKG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.COM_DEPT_PKG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.COOP_RES
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.COOP_RES/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.OUT_SETT
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.OUT_SETT/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.PUB_ETCCODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.PUB_ETCCODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.GIFT_RET_DET
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.GIFT_RET_DET/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRANCH_COMP_OPRT_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRANCH_COMP_OPRT_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.COOP_RES_BKR
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.COOP_RES_BKR/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.COOP_RES_CUS
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.COOP_RES_CUS/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.COOP_RES_PRD
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.COOP_RES_PRD/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRANCH_COMP_OPRT_CODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRANCH_COMP_OPRT_CODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.TLT_ETCCODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.TLT_ETCCODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_GOAL_DETAIL
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_GOAL_DETAIL/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_REQ_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_REQ_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRANCH_COMP_OPRT_SUB
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRANCH_COMP_OPRT_SUB/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_CODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_CODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.OUT_SETT_ITEM
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.OUT_SETT_ITEM/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BG_CATEGORY_EMP_CONFIG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BG_CATEGORY_EMP_CONFIG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_PROPERTY_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_PROPERTY_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.ITEM_STOCK_SUMMARY
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.ITEM_STOCK_SUMMARY/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BG_BUS_EMPLOYEE_MNG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BG_BUS_EMPLOYEE_MNG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.ITEM_OUT_MASTER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.ITEM_OUT_MASTER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_GOAL_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_GOAL_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_EVENT_REMARK
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_EVENT_REMARK/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.EDI2_MASTER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.EDI2_MASTER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_SCHD_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_SCHD_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_CORP_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_CORP_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.EDI2_DOC_TYPE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.EDI2_DOC_TYPE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_MLG_IF
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_MLG_IF/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_HP_RCT
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_HP_RCT/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.DAT_SYS_AUTH
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.DAT_SYS_AUTH/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_WEEK_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_WEEK_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BUS_ETCCODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BUS_ETCCODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_PRPT_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_PRPT_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.DAT_SYS_USER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.DAT_SYS_USER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_CURR_INFO
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_CURR_INFO/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BRC_PUB_ETCCODE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BRC_PUB_ETCCODE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.BUS_WORK_PLACE
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.BUS_WORK_PLACE/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_AGREE_SIGN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_AGREE_SIGN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.OUT_CONFIRM
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.OUT_CONFIRM/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSIN01.CST_CLT_AGRMT
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSIN01.CST_CLT_AGRMT/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSIN01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
