
use database cdc;
use warehouse cdc_wh;


SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HTSML01');


show tasks;

execute task CDC.PUBLIC.HTSML01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HTSML01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HTSML01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HTSML01.JOIN_MASTER_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.JOIN_MASTER_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.APR_DEALTR_DTL
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.APR_DEALTR_DTL/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.JOIN_DEALTR_DIV
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.JOIN_DEALTR_DIV/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_SCS_MAP
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_SCS_MAP/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.JOIN_CARD_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.JOIN_CARD_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.APR_DEALTR_TRN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.APR_DEALTR_TRN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_SVC_TRN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_SVC_TRN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_PNT_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_PNT_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.USE_FIFO_DIV
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.USE_FIFO_DIV/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.SAVE_FIFO_DIV
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.SAVE_FIFO_DIV/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_INTERFACE_LOG
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_INTERFACE_LOG/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.PNT_SUM_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.PNT_SUM_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_MASTER_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_MASTER_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_JOINGROUP_MGT
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_JOINGROUP_MGT/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_SUB_MEM
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_SUB_MEM/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.SAVE_FIFO_TRN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.SAVE_FIFO_TRN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CDE_MASTER
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CDE_MASTER/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.MCT_MASTER_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.MCT_MASTER_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CDE_CATEGORY
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CDE_CATEGORY/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.PTNS_BATSTD_WRK
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.PTNS_BATSTD_WRK/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.CST_GRUP_MST
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.CST_GRUP_MST/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.PRO_NOTICE_SVC
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.PRO_NOTICE_SVC/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.USE_FIFO_TRN
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.USE_FIFO_TRN/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.EXP_MLG_BATSTD_WRK
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.EXP_MLG_BATSTD_WRK/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HTSML01.USE_DEALTR_DTL
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HTSML01.USE_DEALTR_DTL/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HTSML01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
