
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('HUB01');



show tasks;

execute task CDC.PUBLIC.HUB01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'HUB01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.HUB01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.HUB01.CRP_RSPB_AGT_STAF_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_RSPB_AGT_STAF_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_STDG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_STDG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.SCH_PTN_STAF_ADD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.SCH_PTN_STAF_ADD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_DMND_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_DMND_TYPE_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_TYPE_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.SCH_MEMC_SITE_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.SCH_MEMC_SITE_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_PRS_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_PRS_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_CMNTY_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_CMNTY_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.SCH_PNT_TSUM_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.SCH_PNT_TSUM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_SHPN_RFD_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_SHPN_RFD_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_CRPN_MEM_MLG_MST_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_CRPN_MEM_MLG_MST_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_DMND_EXNS_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DMND_EXNS_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_CATG_SSC_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_CATG_SSC_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_UP_CATG_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_UP_CATG_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_RSPB_AGT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_RSPB_AGT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_CRPN_RPPR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_CRPN_RPPR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CSI_RSC_SVR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CSI_RSC_SVR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_CATG_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_CATG_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.SCH_PTN_MAIN_SCRN_CONF_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.SCH_PTN_MAIN_SCRN_CONF_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_CRPN_MAIN_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_CRPN_MAIN_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CRP_RSPB_TYPE_PER_RPPR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CRP_RSPB_TYPE_PER_RPPR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.CSI_OVP_SVR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.CSI_OVP_SVR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_DTRB_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DTRB_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_DTRB_HIST_ADD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_DTRB_HIST_ADD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.HUB01.VOC_CMPN_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/HUB01.VOC_CMPN_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.HUB01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
