
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('PKG01');




show tasks;

execute task CDC.PUBLIC.PKG01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'PKG01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.PKG01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_UPD_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_UPD_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_RES_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_RES_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PDS_PKG_LND_COST_DTL_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PDS_PKG_LND_COST_DTL_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_NTYT_CNTG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_NTYT_CNTG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_ITNR_CITY_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_ITNR_CITY_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_CLPSN_PECN_S
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_CLPSN_PECN_S/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_JNT_EVNT_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_JNT_EVNT_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_CNTNT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_CNTNT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_BIDN_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_BIDN_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RPPD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RPPD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_TRVL_EXPN_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_TRVL_EXPN_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PDS_PKG_LND_COST_SETT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PDS_PKG_LND_COST_SETT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_BROF_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_BROF_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_SHPN_CNTR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_SHPN_CNTR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_PROD_MSTR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_PROD_MSTR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_THM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_THM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_GOLF_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_GOLF_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_SHPN_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_SHPN_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RPPD_TAG_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RPPD_TAG_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_RES_UPD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_RES_UPD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_SCHD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_SCHD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_GUID_AGSN_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_GUID_AGSN_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_RCCT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_RCCT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_PROM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_PROM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PDS_PKG_LND_COST_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PDS_PKG_LND_COST_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_GUID_AGSN_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_GUID_AGSN_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_SPCL_STPL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_SPCL_STPL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_PROD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_PROD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_SCHD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_SCHD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_SIM_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_SIM_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_AI_SCHD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_AI_SCHD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_SHPSHP_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_SHPSHP_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_HTL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_HTL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_SCHD_LAND_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_SCHD_LAND_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_AI_SCHD_TMPL_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_AI_SCHD_TMPL_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_CTRC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_CTRC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_SCHD_HTL_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_SCHD_HTL_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RVNS_DEPT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RVNS_DEPT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_BFHD_ISUE_MGMT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_BFHD_ISUE_MGMT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SIM_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SIM_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_ANSR_SEND_H
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_ANSR_SEND_H/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_GDWD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_GDWD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_DMND_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_DMND_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RPPD_VIST_CITY_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RPPD_VIST_CITY_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RPPD_CNTNT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RPPD_CNTNT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_AIR_INV_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_AIR_INV_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_AREA_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_AREA_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PDS_PKG_LND_COST_FNSMT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PDS_PKG_LND_COST_FNSMT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_PROD_CTPR_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_PROD_CTPR_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SLPD_SCHD_GOFC_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SLPD_SCHD_GOFC_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_RES_RMK_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_RES_RMK_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_CHC_STSNG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_CHC_STSNG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_RPPD_MSTR_R
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_RPPD_MSTR_R/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_RSPB_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_RSPB_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_DAY_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_DAY_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_TC_ASGN_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_TC_ASGN_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_QUOT_MGR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_QUOT_MGR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_THM_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_THM_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_FLXB_AMT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_FLXB_AMT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_GUID_WRDNG_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_GUID_WRDNG_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PDS_PKG_LND_COST_INVC_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PDS_PKG_LND_COST_INVC_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SALE_PROD_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SALE_PROD_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SNDG_PRPN_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SNDG_PRPN_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_SNDG_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_SNDG_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_RES_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_RES_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_RES_UPD_L
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_RES_UPD_L/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.COM_PKG_PROD_SPRTR_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.COM_PKG_PROD_SPRTR_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.PPD_PKG_TC_PRAR_INFO_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.PPD_PKG_TC_PRAR_INFO_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.SAC_PKG_SPPD_SCHD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.SAC_PKG_SPPD_SCHD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.PKG01.RSV_PKG_TRVL_CNDM_AGRT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/PKG01.RSV_PKG_TRVL_CNDM_AGRT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.PKG01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
