
use database cdc;
use warehouse cdc_wh;

SELECT
    '''' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ''',' 
AS CALL_SCRIPTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('STT01');



show tasks;

execute task CDC.PUBLIC.STT01_TABLE_INITIAL_TASK ;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'STT01_TABLE_INITIAL_TASK'
     -- , ERROR_ONLY => TRUE 
     )) ORDER BY SCHEDULED_TIME DESC LIMIT 20;


select * from CDC.CST01.CST_NNMM_M;




CREATE OR REPLACE TASK CDC.PUBLIC.STT01_TABLE_INITIAL_TASK
    WAREHOUSE = 'CDC_WH'
    SCHEDULE = NULL
AS
BEGIN


COPY INTO CDC.STT01.FSU_COM_BSC_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.FSU_COM_BSC_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_TKT_SETT_FEE_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_TKT_SETT_FEE_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_SETT_APRV_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_SETT_APRV_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.DEP_UNFY_RECM_PAY_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_UNFY_RECM_PAY_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.DEP_CARD_AUTH_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_CARD_AUTH_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_AIR_SETT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_AIR_SETT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_LND_COST_SETT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_LND_COST_SETT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_NSTG_SETT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_NSTG_SETT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.REC_UNCL_RFD_RES_S
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.REC_UNCL_RFD_RES_S/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_IDVL_EXPN_SETT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_IDVL_EXPN_SETT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_JNT_EXPN_SETT_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_JNT_EXPN_SETT_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_AIR_APRV_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_AIR_APRV_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_SETT_APRV_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_SETT_APRV_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_LND_RFD_SETT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_LND_RFD_SETT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.FSU_USR_ATHR_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.FSU_USR_ATHR_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_PROD_SETT_M
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_PROD_SETT_M/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_TKT_SETT_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_TKT_SETT_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.FSU_SETT_ACNT_CD_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.FSU_SETT_ACNT_CD_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.FSU_COM_DTL_C
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.FSU_COM_DTL_C/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.FSU_CLSG_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.FSU_CLSG_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.DEP_DEPR_NM_X
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_DEPR_NM_X/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.REC_UNCL_RES_S
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.REC_UNCL_RES_S/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.SET_LND_COST_RFD_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.SET_LND_COST_RFD_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;


COPY INTO CDC.STT01.DEP_CARD_AUTH_D
FROM '@"STG_EXTERNAL"."CDC"."NEON"/STT01.DEP_CARD_AUTH_D/'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (TYPE = PARQUET)
-- FILE_FORMAT = (FORMAT_NAME = 'STG_EXTERNAL.STT01.PARQUET')
PATTERN = '.*\.parquet$'
FORCE = TRUE;



END;
