
use role sysadmin;

use role RL_DBT_FUNC_RW;

use role RL_DBT_USER; 

select current_role();

/* 
    TASK 수행 방법
        >> 일회성 수행
*/

execute task DWDM.PUBLIC.ETL_CRM_TRUNCATE_AND_COPY;

/* 
    TASK 조회
*/

select * from table(dwdm.information_schema.task_history()) 
where name = 'ETL_CRM_TRUNCATE_AND_COPY'
order by scheduled_time desc
;

select * from dwdm.information_schema.tables
where table_name like '%IFPD%'
  and table_schema = 'CRM'
;



/* 
    TASK 수행 시 이슈발생 내역

Cannot execute task , EXECUTE TASK privilege must be granted to owner role


Uncaught exception of type 'STATEMENT_ERROR' on line 20 at position 9 : SQL compilation error:
Table 'DWDM.CRM.IFPD_CROSS_PROD_RCMN_M' does not exist



Uncaught exception of type 'STATEMENT_ERROR' on line 20 at position 9 : SQL compilation error:
Table 'DWDM.CRM.IFPD_CROSS_PROD_RCMN_M' does not exist
;
Uncaught exception of type 'STATEMENT_ERROR' on line 20 at position 9 : SQL compilation error:
Table 'DWDM.CRM.IFPD_CROSS_PROD_RCMN_M' does not exist

Uncaught exception of type 'STATEMENT_ERROR' on line 3 at position 9 : SQL access control error:
Insufficient privileges to operate on table 'IFPD_CROSS_PROD_RCMN_M'.

;
*/




/*
    CRM 스키마 초기적재 PROCEDURE 생성문
*/

CREATE OR REPLACE PROCEDURE DWDM.PUBLIC.ETL_CRM_TRUNCATE_AND_COPY()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  -- Step 1: Truncate all tables
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IBCO_CITY_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IBSE_RES_SETT_00_T);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IBSE_RES_SETT_01_T);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IBSE_RES_SETT_02_T);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IBSE_RES_SETT_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_CROSS_PROD_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_CROSS_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_CUST_BNR_INFO_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_CUST_BNR_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_CUST_SGMT_UNFY_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_HANALIVE_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_PLNR_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_PROD_ITNR_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_PROD_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_PUSH_AUTO_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_PUSH_GRP_D);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_SCH_PROD_RCMN_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_SRWR_RCMN_ADRS_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.CRM.IFPD_SRWR_RCMN_M);
  AWAIT ALL;

  -- Step 2: Copy data to all tables
  ASYNC (COPY INTO DWDM.CRM.IBCO_CITY_C FROM $$@STG_EXTERNAL.CDC.COBALT/CRMDEV01.IBCO_CITY_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IBSE_RES_SETT_00_T FROM $$@STG_EXTERNAL.CDC.COBALT/CRMDEV01.IBSE_RES_SETT_00_T/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IBSE_RES_SETT_01_T FROM $$@STG_EXTERNAL.CDC.COBALT/CRMDEV01.IBSE_RES_SETT_01_T/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IBSE_RES_SETT_02_T FROM $$@STG_EXTERNAL.CDC.COBALT/CRMDEV01.IBSE_RES_SETT_02_T/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IBSE_RES_SETT_M FROM $$@STG_EXTERNAL.CDC.COBALT/CRMDEV01.IBSE_RES_SETT_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_CROSS_PROD_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_CROSS_PROD_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_CROSS_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_CROSS_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_CUST_BNR_INFO_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_CUST_BNR_INFO_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_CUST_BNR_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_CUST_BNR_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_CUST_SGMT_UNFY_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_CUST_SGMT_UNFY_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_HANALIVE_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_HANALIVE_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_PLNR_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_PLNR_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_PROD_ITNR_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_PROD_ITNR_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_PROD_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_PROD_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_PUSH_AUTO_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_PUSH_AUTO_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_PUSH_GRP_D FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_PUSH_GRP_D/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_SCH_PROD_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_SCH_PROD_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_SRWR_RCMN_ADRS_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_SRWR_RCMN_ADRS_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.CRM.IFPD_SRWR_RCMN_M FROM $$@STG_EXTERNAL.CDC.COBALT/CCS01.IFPD_SRWR_RCMN_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = ''.*\\.parquet$'' FORCE = TRUE);
  AWAIT ALL;
  RETURN ''All CCS01 operations completed - 19 tables truncated and loaded'';
END';


/*
    CRM 스키마 초기적재 TASK 생성문
*/

create or replace task DWDM.PUBLIC.ETL_CRM_TRUNCATE_AND_COPY
warehouse = compute_wh
AS
call DWDM.PUBLIC.ETL_CRM_TRUNCATE_AND_COPY();