
use database dwdm;
use warehouse compute_wh;
use role sysadmin;


/* 
    TASK 수행 방법
        >> 일회성 수행
*/

execute task DWDM.PUBLIC.ETL_MSS01_TRUNCATE_AND_COPY;


/* 
    TASK 조회
*/

select * from dwdm.information_schema.tables
where table_schema = 'MSS01'
and row_count > 0
;

select * from table(information_schema.task_history()) 
where name = 'ETL_MSS01_TRUNCATE_AND_COPY'
;




/*
    MSS01 스키마 초기적재 PROCEDURE 생성문
*/

CREATE OR REPLACE PROCEDURE DWDM.PUBLIC.ETL_MSS01_TRUNCATE_AND_COPY()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
  -- Step 1: Truncate all tables
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_CMPY_HMRS_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_HAS_PKG_SLPD);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_HAS_USE_PECN_X);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_HTL_SALE_PROM_GOAL_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_HTL_SLCO_VI_GOAL_D);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_IBCO_QRTR_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_IBCO_SMNL_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_IBCO_WK_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_IBCO_YM_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_IBCO_YR_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_ORG_INFO_LST_MNTH_C_SAP);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_ORG_INFO_LST_MNTH_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_ORG_INFO_M_SAP);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_OVBF_CURR_INFO_C_YY);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_OVBF_CURR_INFO_C);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_PKG_RPPD_M);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_PKG_SLPD_PROM_D);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_PTN_M_AGNT);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_PTN_M_AIR);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_PTN_M_LAND);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_SAP_BALA_BEF_BDGT_VER);
  ASYNC (TRUNCATE TABLE IF EXISTS DWDM.MSS01.SQL_USR_HMRS_M);
  AWAIT ALL;

  -- Step 2: Copy data to all tables
  ASYNC (COPY INTO DWDM.MSS01.SQL_CMPY_HMRS_M FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_CMPY_HMRS_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_HAS_PKG_SLPD FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_HAS_PKG_SLPD/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_HAS_USE_PECN_X FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_HAS_USE_PECN_X/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_HTL_SALE_PROM_GOAL_M FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_HTL_SALE_PROM_GOAL_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_HTL_SLCO_VI_GOAL_D FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_HTL_SLCO_VI_GOAL_D/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_IBCO_QRTR_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_IBCO_QRTR_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_IBCO_SMNL_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_IBCO_SMNL_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_IBCO_WK_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_IBCO_WK_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_IBCO_YM_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_IBCO_YM_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_IBCO_YR_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_IBCO_YR_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_ORG_INFO_LST_MNTH_C_SAP FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_ORG_INFO_LST_MNTH_C_SAP/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_ORG_INFO_LST_MNTH_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_ORG_INFO_LST_MNTH_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_ORG_INFO_M_SAP FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_ORG_INFO_M_SAP/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_OVBF_CURR_INFO_C_YY FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_OVBF_CURR_INFO_C_YY/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_OVBF_CURR_INFO_C FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_OVBF_CURR_INFO_C/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_PKG_RPPD_M FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_PKG_RPPD_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_PKG_SLPD_PROM_D FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_PKG_SLPD_PROM_D/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_PTN_M_AGNT FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_PTN_M_AGNT/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_PTN_M_AIR FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_PTN_M_AIR/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_PTN_M_LAND FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_PTN_M_LAND/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_SAP_BALA_BEF_BDGT_VER FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_SAP_BALA_BEF_BDGT_VER/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  ASYNC (COPY INTO DWDM.MSS01.SQL_USR_HMRS_M FROM $$@STG_EXTERNAL.CDC.COBALT/MSS01.SQL_USR_HMRS_M/$$ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = ( TYPE = PARQUET, REPLACE_INVALID_CHARACTERS = TRUE ) PATTERN = '.*\.parquet$' FORCE = TRUE);
  AWAIT ALL;
  RETURN 'All MSS01 operations completed - 22 tables truncated and loaded';
END;


/*
    MSS01 스키마 초기적재 TASK 생성문
*/

create or replace task DWDM.PUBLIC.ETL_MSS01_TRUNCATE_AND_COPY
warehouse = compute_wh
AS
call DWDM.PUBLIC.ETL_MSS01_TRUNCATE_AND_COPY();


