-- Copy History 로 이슈 감지 
WITH failed AS (
    SELECT
        *
    FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
    WHERE STATUS != 'Loaded'
      AND LAST_LOAD_TIME >= DATEADD('day', -5, CURRENT_TIMESTAMP())
)
SELECT
    MAX(LAST_LOAD_TIME) AS LAST_FAIL_TIME, -- 마지막 실패 시간 
    STATUS,
    STAGE_LOCATION,
    CONCAT(PIPE_CATALOG_NAME, '.', PIPE_SCHEMA_NAME, '.', PIPE_NAME) AS PIPE_PATH,   
    CONCAT(TABLE_CATALOG_NAME, '.', TABLE_SCHEMA_NAME, '.', TABLE_NAME) AS TABLE_PATH,  -- 타겟 테이블 
    FIRST_ERROR_MESSAGE,  --- 에러 메세지
    COUNT(*) AS FAIL_COUNT,  -- 실패 횟수
    SUM(ROW_PARSED) AS MAX_ROW_PARSED,  -- 대상 Row 개수
    ARRAY_AGG(DISTINCT FILE_NAME) AS FILE_NAME_LIST  -- ← 파일명 리스트
FROM failed
GROUP BY
    STATUS,
    STAGE_LOCATION,
    TABLE_CATALOG_NAME,
    TABLE_SCHEMA_NAME,
    TABLE_NAME,
    PIPE_CATALOG_NAME,
    PIPE_SCHEMA_NAME,
    PIPE_NAME,
    FIRST_ERROR_MESSAGE
ORDER BY
    TABLE_SCHEMA_NAME, TABLE_NAME;


-- Copy History 로 이슈 감지 
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PROCEDURES;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY;