/*
CDC 동기화 시키지 않은 컬럼 제거
*/

/* CDC 미동기화 컬럼 제거 */
ALTER TABLE dwdm.inf01.IBSE_CARD_AUTH_M drop COLUMN CARD_AUTH_NUM;
ALTER TABLE dwdm.inf01.IBSE_CARD_AUTH_M drop COLUMN CUST_IDNTFC_ID;
ALTER TABLE dwdm.inf01.IBSE_CARD_AUTH_M drop COLUMN PYR_NM;
ALTER TABLE dwdm.inf01.IBSE_CARD_AUTH_M drop COLUMN PAY_MPN;
ALTER TABLE dwdm.inf01.IBSE_CARD_AUTH_M drop COLUMN CI;

/* CDC 미동기화 컬럼 제거 */
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN CUST_GNDR_DV_CD; /*고객성별구분코드*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN REQR_KO_NM; /*신청자한글명*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN REQR_TEL; /*신청자전화번호*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN REQR_EML; /*신청자이메일*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN CUST_KO_NM; /*고객한글명*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN CUST_EML; /*고객이메일*/
ALTER TABLE dwdm.inf01.IBCU_VOC_RCPN_X drop COLUMN CUST_TEL; /*고객전화번호*/


ALTER TABLE DWDM.INF01.IBCO_PTN_M DROP COLUMN AIRL_RPPR_TEL;
ALTER TABLE DWDM.INF01.IBCO_PTN_M DROP COLUMN INDV_AIR_RPPR_TEL;

ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN CMPA_TEL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN EMRG_TEL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN FAXN;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN EML;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN BSC_ADRS;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN DTL_ADRS;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN HOME_TEL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN ACCN;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN IP_PHN_TEL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN INSD_CUST_IDNTFC_VAL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN EXTR_CUST_IDNTFC_VAL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN EXTR_CUST_IDNTFC_VER_VAL;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN ROAD_BSC_ADRS;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN ROAD_DTL_ADRS;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN STAF_MPN;
ALTER TABLE DWDM.INF01.IBCO_PTN_STAF_D DROP COLUMN MEMC_MEM_ID;

ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN MPN;
ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN TEL;
ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN FAXN;
ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN HANA_EML_ADRS;
ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN EXTR_EML_ADRS;
ALTER TABLE DWDM.INF01.IBCO_USR_HMRS_M DROP COLUMN BTHD;

ALTER TABLE DWDM.INF01.IBCO_OVRS_PTN_STAF_D DROP COLUMN TEL;
ALTER TABLE DWDM.INF01.IBCO_OVRS_PTN_STAF_D DROP COLUMN EML;

ALTER TABLE DWDM.INF01.IBSA_HTL_RES_PROM_D DROP COLUMN HTL_PROM_RMK; /* 호텔프로모션비고 */


/*  */

ALTER TABLE DWDM.INF01.IBSA_ONLN_QTSH_M DROP COLUMN AGT_DV_CD; /* 대리점구분코드 */