-- Database and Schema Setup
CREATE DATABASE IF NOT EXISTS "SAP";
CREATE SCHEMA IF NOT EXISTS "SAP"."SAPSR3";


-- Table Definitions
CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOT596M" (    
    "MANDT"       VARCHAR  DEFAULT '000'      NOT NULL,
    "GUBUN"       VARCHAR  DEFAULT ' '        NOT NULL,
    "IOACC"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ZCLASSLTXT"  VARCHAR  DEFAULT ' '        NOT NULL,
    "ZCLASSMTXT"  VARCHAR  DEFAULT ' '        NOT NULL,
    "ZCLASSSTXT"  VARCHAR  DEFAULT ' '        NOT NULL,
    "IOACCTXT"    VARCHAR  DEFAULT ' '        NOT NULL,
    "UNAME"       VARCHAR  DEFAULT ' '        NOT NULL,
    "DATUM"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "ERZET"       VARCHAR  DEFAULT '000000'   NOT NULL
);

	
CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOT0501N" (    
    "MANDT"   VARCHAR  DEFAULT '000'      NOT NULL,
    "KOKRS"   VARCHAR  DEFAULT ' '        NOT NULL,
    "KOSTL"   VARCHAR  DEFAULT ' '        NOT NULL,
    "DATBI"   VARCHAR  DEFAULT '00000000' NOT NULL,
    "ZKSDO"   VARCHAR  DEFAULT ' '        NOT NULL,
    "DATAB"   VARCHAR  DEFAULT '00000000' NOT NULL,
    "BUKRS"   VARCHAR  DEFAULT ' '        NOT NULL,
    "DATUM"   VARCHAR  DEFAULT '00000000' NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOT0031" (    
    "MANDT"       VARCHAR  DEFAULT '000' NOT NULL,
    "KSTAR_L3"    VARCHAR  DEFAULT ' '   NOT NULL,
    "KTEXT_L3"    VARCHAR  DEFAULT ' '   NOT NULL
);


-- 참고 사항 : 원천 DB 에서는 VIEW 로 생성되어 있으나, Snowflake 에는 Table 로 생성 
CREATE OR REPLACE TABLE "SAP"."SAPSR3"."V_AUART" (    
    "CLIENT"    VARCHAR  NOT NULL,
    "AUART"     VARCHAR  NOT NULL,
    "AUTYP"     VARCHAR  NOT NULL,
    "TXT"       VARCHAR  NOT NULL,
    "SPRAS"     VARCHAR  NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."DD07T" (    
    "DOMNAME"     VARCHAR  DEFAULT ' '    NOT NULL,
    "DDLANGUAGE"  VARCHAR  DEFAULT ' '    NOT NULL,
    "AS4LOCAL"    VARCHAR  DEFAULT ' '    NOT NULL,
    "VALPOS"      VARCHAR  DEFAULT '0000' NOT NULL,
    "AS4VERS"     VARCHAR  DEFAULT '0000' NOT NULL,
    "DDTEXT"      VARCHAR  DEFAULT ' '    NOT NULL,
    "DOMVAL_LD"   VARCHAR  DEFAULT ' '    NOT NULL,
    "DOMVAL_HD"   VARCHAR  DEFAULT ' '    NOT NULL,
    "DOMVALUE_L"  VARCHAR  DEFAULT ' '    NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."CSKU" (    
    "MANDT"   VARCHAR  DEFAULT '000' NOT NULL,
    "SPRAS"   VARCHAR  DEFAULT ' '   NOT NULL,
    "KTOPL"   VARCHAR  DEFAULT ' '   NOT NULL,
    "KSTAR"   VARCHAR  DEFAULT ' '   NOT NULL,
    "KTEXT"   VARCHAR  DEFAULT ' '   NOT NULL,
    "LTEXT"   VARCHAR  DEFAULT ' '   NOT NULL,
    "MCTXT"   VARCHAR  DEFAULT ' '   NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."CSKA" (    
    "MANDT"       VARCHAR  DEFAULT '000'      NOT NULL,
    "KTOPL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KSTAR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ERSDA"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "USNAM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "STEKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ZAHKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KSTSN"       VARCHAR  DEFAULT ' '        NOT NULL,
    "FUNC_AREA"   VARCHAR  DEFAULT ' '        NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."AUFK" (    
    "MANDT"       VARCHAR  DEFAULT '000'      NOT NULL,
    "AUFNR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "AUART"       VARCHAR  DEFAULT ' '        NOT NULL,
    "AUTYP"       VARCHAR  DEFAULT '00'       NOT NULL,
    "REFNR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ERNAM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ERDAT"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "AENAM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "AEDAT"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "KTEXT"       VARCHAR  DEFAULT ' '        NOT NULL,
    "LTEXT"       VARCHAR  DEFAULT ' '        NOT NULL,
    "BUKRS"       VARCHAR  DEFAULT ' '        NOT NULL,
    "WERKS"       VARCHAR  DEFAULT ' '        NOT NULL,
    "GSBER"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KOKRS"       VARCHAR  DEFAULT ' '        NOT NULL,
    "CCKEY"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KOSTV"       VARCHAR  DEFAULT ' '        NOT NULL,
    "STORT"       VARCHAR  DEFAULT ' '        NOT NULL,
    "SOWRK"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ASTKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "WAERS"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ASTNR"       VARCHAR  DEFAULT '00'       NOT NULL,
    "STDAT"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "ESTNR"       VARCHAR  DEFAULT '00'       NOT NULL,
    "PHAS0"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PHAS1"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PHAS2"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PHAS3"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PDAT1"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "PDAT2"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "PDAT3"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "IDAT1"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "IDAT2"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "IDAT3"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "OBJID"       VARCHAR  DEFAULT ' '        NOT NULL,
    "VOGRP"       VARCHAR  DEFAULT ' '        NOT NULL,
    "LOEKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PLGKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KVEWE"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KAPPL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KALSM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ZSCHL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ABKRS"       VARCHAR  DEFAULT '00'       NOT NULL,
    "KSTAR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KOSTL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "SAKNR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "SETNM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "CYCLE"       VARCHAR  DEFAULT ' '        NOT NULL,
    "SDATE"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "SEQNR"       VARCHAR  DEFAULT '0000'     NOT NULL,
    "USER0"       VARCHAR  DEFAULT ' '        NOT NULL,
    "USER1"       VARCHAR  DEFAULT ' '        NOT NULL,
    "USER2"       VARCHAR  DEFAULT ' '        NOT NULL,
    "USER3"       VARCHAR  DEFAULT ' '        NOT NULL,
    "USER4"       NUMBER   DEFAULT 0          NOT NULL,
    "USER5"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "USER6"       VARCHAR  DEFAULT ' '        NOT NULL,
    "USER7"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "USER8"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "USER9"       VARCHAR  DEFAULT ' '        NOT NULL,
    "OBJNR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PRCTR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PSPEL"       VARCHAR  DEFAULT '00000000' NOT NULL,
    "AWSLS"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ABGSL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "TXJCD"       VARCHAR  DEFAULT ' '        NOT NULL,
    "FUNC_AREA"   VARCHAR  DEFAULT ' '        NOT NULL,
    "SCOPE"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PLINT"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KDAUF"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KDPOS"       VARCHAR  DEFAULT '000000'   NOT NULL,
    "AUFEX"       VARCHAR  DEFAULT ' '        NOT NULL,
    "IVPRO"       VARCHAR  DEFAULT ' '        NOT NULL,
    "LOGSYSTEM"   VARCHAR  DEFAULT ' '        NOT NULL,
    "FLG_MLTPS"   VARCHAR  DEFAULT ' '        NOT NULL,
    "ABUKR"       VARCHAR  DEFAULT ' '        NOT NULL,
    "AKSTL"       VARCHAR  DEFAULT ' '        NOT NULL,
    "SIZECL"      VARCHAR  DEFAULT ' '        NOT NULL,
    "IZWEK"       VARCHAR  DEFAULT ' '        NOT NULL,
    "UMWKZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "KSTEMPF"     VARCHAR  DEFAULT ' '        NOT NULL,
    "ZSCHM"       VARCHAR  DEFAULT ' '        NOT NULL,
    "PKOSA"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ANFAUFNR"    VARCHAR  DEFAULT ' '        NOT NULL,
    "PROCNR"      VARCHAR  DEFAULT '000000000000' NOT NULL,
    "PROTY"       VARCHAR  DEFAULT ' '        NOT NULL,
    "RSORD"       VARCHAR  DEFAULT ' '        NOT NULL,
    "BEMOT"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ADRNRA"      VARCHAR  DEFAULT ' '        NOT NULL,
    "ERFZEIT"     VARCHAR  DEFAULT '000000'   NOT NULL,
    "AEZEIT"      VARCHAR  DEFAULT '000000'   NOT NULL,
    "CSTG_VRNT"   VARCHAR  DEFAULT ' '        NOT NULL,
    "COSTESTNR"   VARCHAR  DEFAULT '000000000000' NOT NULL,
    "VERAA_USER"  VARCHAR  DEFAULT ' '        NOT NULL,
    "VNAME"       VARCHAR  DEFAULT ' '        NOT NULL,
    "RECID"       VARCHAR  DEFAULT ' '        NOT NULL,
    "ETYPE"       VARCHAR  DEFAULT ' '        NOT NULL,
    "OTYPE"       VARCHAR  DEFAULT ' '        NOT NULL,
    "JV_JIBCL"    VARCHAR  DEFAULT ' '        NOT NULL,
    "JV_JIBSA"    VARCHAR  DEFAULT ' '        NOT NULL,
    "JV_OCO"      VARCHAR  DEFAULT ' '        NOT NULL,
    "VAPLZ"       VARCHAR  DEFAULT ' '        NOT NULL,
    "WAWRK"       VARCHAR  DEFAULT ' '        NOT NULL,
    "FERC_IND"    VARCHAR  DEFAULT ' '        NOT NULL
);

create or replace TABLE SAP.SAPSR3.ZCOT596 (
	MANDT VARCHAR(16777216),
	BUKRS VARCHAR(16777216),
	PERIO VARCHAR(16777216),
	PLIKZ VARCHAR(16777216),
	VERSN VARCHAR(16777216),
	KOSTL VARCHAR(16777216),
	GUBUN VARCHAR(16777216),
	IOACC VARCHAR(16777216),
	WKGBTR NUMBER(38,0),
	TWAER VARCHAR(16777216),
	UNAME VARCHAR(16777216),
	DATUM VARCHAR(16777216),
	ERZET VARCHAR(16777216),
	ETL_UPD_DTTM TIMESTAMP_LTZ(9)
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOT577" (    
    "MANDT"   VARCHAR  DEFAULT '000'      NOT NULL,
    "KOKRS"   VARCHAR  DEFAULT ' '        NOT NULL,
    "BUKRS"   VARCHAR  DEFAULT ' '        NOT NULL,
    "GJAHR"   VARCHAR  DEFAULT '0000'     NOT NULL,
    "PERDE"   VARCHAR  DEFAULT '000'      NOT NULL,
    "WRTTP"   VARCHAR  DEFAULT ' '        NOT NULL,
    "VERSN"   VARCHAR  DEFAULT ' '        NOT NULL,
    "ZKSDO"   VARCHAR  DEFAULT ' '        NOT NULL,
    "KOSTL"   VARCHAR  DEFAULT ' '        NOT NULL,
    "ZGUBUN2" VARCHAR  DEFAULT ' '        NOT NULL,
    "TWAER"   VARCHAR  DEFAULT ' '        NOT NULL,
    "ZWTG001" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG002" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG003" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG004" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG005" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG006" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG007" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG008" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG009" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG010" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG011" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG012" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG013" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG014" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG101" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG102" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG103" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG104" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG105" NUMBER   DEFAULT 0          NOT NULL,
    "ZWTG106" NUMBER   DEFAULT 0          NOT NULL,
    "UNAME"   VARCHAR2 DEFAULT ' '        NOT NULL,
    "DATUM"   VARCHAR2 DEFAULT '00000000' NOT NULL,
    "ERZET"   VARCHAR2 DEFAULT '000000'   NOT NULL
);


/* 20260210 G_SEQ_07_08_FACT_PF_DAY 에서 사용중인 SAP 테이블 추가
    배치에서 사용중인 컬럼만 생성  
 */

 CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOT083" (
  "MANDT"    VARCHAR(9)   DEFAULT '000'      NOT NULL, 
	"BUKRS"    VARCHAR(12)  DEFAULT ' '        NOT NULL, 
	"PERIO"    VARCHAR(18)  DEFAULT '000000'   NOT NULL, 
	"PLIKZ"    VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"VERSN"    VARCHAR(9)   DEFAULT ' '        NOT NULL, 
	"KOSTL"    VARCHAR(30)  DEFAULT ' '        NOT NULL, 
	"GUBUN"    VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"IOACC"    VARCHAR(36)  DEFAULT ' '        NOT NULL, 
	"KSTAR"    VARCHAR(30)  DEFAULT ' '        NOT NULL, 
	"KSTAR_L3" VARCHAR(30)  DEFAULT ' '        NOT NULL, 
	"SHKZG"    VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"ZGUBUN2"  VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"ZGUBUN3"  VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"ZGUBUN4"  VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"ZCLASSL"  VARCHAR(12)  DEFAULT ' '        NOT NULL, 
	"ZCLASSM"  VARCHAR(12)  DEFAULT ' '        NOT NULL, 
	"ZCLASSS"  VARCHAR(15)  DEFAULT ' '        NOT NULL, 
	"ZKSDO"    VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"KOSTL2"   VARCHAR(30)  DEFAULT ' '        NOT NULL, 
	"TWAER"    VARCHAR(15)  DEFAULT ' '        NOT NULL, 
	"WKGBTR"   NUMBER(15,2)  DEFAULT 0          NOT NULL, 
	"COST_G"   VARCHAR(102) DEFAULT ' '        NOT NULL, 
	"UNAME"    VARCHAR(36)  DEFAULT ' '        NOT NULL, 
	"DATUM"    VARCHAR(24)  DEFAULT '00000000' NOT NULL, 
	"ERZET"    VARCHAR(18)  DEFAULT '000000'   NOT NULL, 
	"POST"     VARCHAR(3)   DEFAULT ' '        NOT NULL, 
	"AUART"    VARCHAR(12)  DEFAULT ' '        NOT NULL, 
	"ZGUBUN"   VARCHAR(3)   DEFAULT ' '        NOT NULL
);

CREATE OR REPLACE TABLE "SAP"."SAPSR3"."T003P" (
  "CLIENT" VARCHAR(9)   DEFAULT '000' NOT NULL, 
	"SPRAS"  VARCHAR(3)   DEFAULT ' '   NOT NULL, 
	"AUART"  VARCHAR(12)  DEFAULT ' '   NOT NULL, 
	"TXT"    VARCHAR(120) DEFAULT ' '   NOT NULL
);
 
CREATE OR REPLACE TABLE "SAP"."SAPSR3"."ZCOPE_SIL" (    
	"MANDT"        VARCHAR(9)   DEFAULT '000'  NOT NULL ,
	"KOKRS"        VARCHAR(12)  DEFAULT ' '    NOT NULL ,
	"BUKRS"        VARCHAR(12)  DEFAULT ' '    NOT NULL ,
	"GJAHR"        VARCHAR(12)  DEFAULT '0000' NOT NULL ,
	"KOSTL"        VARCHAR(30)  DEFAULT ' '    NOT NULL ,
	"PERIO"        VARCHAR(9)   DEFAULT '000'  NOT NULL ,
	"VERSN"        VARCHAR(9)   DEFAULT ' '    NOT NULL ,
	"VRGNG"        VARCHAR(12)  DEFAULT ' '    NOT NULL ,
	"BELNR"        VARCHAR(30)  DEFAULT ' '    NOT NULL ,
	"BUZEI"        VARCHAR(9)   DEFAULT '000'  NOT NULL ,
	"BLTXT"        VARCHAR(150) DEFAULT ' '    NOT NULL ,
	"ZFLAG"        VARCHAR(3)   DEFAULT ' '    NOT NULL ,
	"ZMODIFY"      VARCHAR(3)   DEFAULT ' '    NOT NULL ,
	"ZMODSEQ"      VARCHAR(9)   DEFAULT '000'  NOT NULL ,
	"KSTAR1"       VARCHAR(30)  DEFAULT ' '    NOT NULL ,
	"KSTAR"        VARCHAR(30)  DEFAULT ' '    NOT NULL ,
	"AUFNR"        VARCHAR(36)  DEFAULT ' '    NOT NULL ,
	"AUFNR_T"      VARCHAR(120) DEFAULT ' '    NOT NULL ,
	"KOSTL_GI"     VARCHAR(30)  DEFAULT ' '    NOT NULL ,
	"ZFIELD_BUN"   VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"ZFIELD_BU"    VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"ZFIELD_SA"    VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"ZFIELD_YEA"   VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"ZFIELD_YEA_T" VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"KTEXT"        VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"KOSTL_T"      VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"KOSTL_GI_T"   VARCHAR(60)  DEFAULT ' '    NOT NULL ,
	"WTGBTR_GA"    NUMBER(15,2)  DEFAULT 0     NOT NULL ,
	"WTGBTR_SIL"   NUMBER(15,2)  DEFAULT 0     NOT NULL ,
	"OWAER"        VARCHAR(15)  DEFAULT ' '    NOT NULL ,
	"WTGBTR"       NUMBER(15,2)  DEFAULT 0     NOT NULL
);


CREATE OR REPLACE TABLE "SAP"."SAPSR3"."CSKS" (
  "MANDT"      VARCHAR(9)   DEFAULT '000'      NOT NULL , 
	"KOKRS"      VARCHAR(12)  DEFAULT ' '        NOT NULL , 
	"KOSTL"      VARCHAR(30)  DEFAULT ' '        NOT NULL , 
	"DATBI"      VARCHAR(24)  DEFAULT '00000000' NOT NULL , 
	"DATAB"      VARCHAR(24)  DEFAULT '00000000' NOT NULL 
);



CREATE OR REPLACE TABLE "SAP"."SAPSR3"."CSKT" (
  "MANDT" VARCHAR(9)   DEFAULT '000'      NOT NULL , 
	"SPRAS" VARCHAR(3)   DEFAULT ' '        NOT NULL , 
	"KOKRS" VARCHAR(12)  DEFAULT ' '        NOT NULL , 
	"KOSTL" VARCHAR(30)  DEFAULT ' '        NOT NULL , 
	"DATBI" VARCHAR(24)  DEFAULT '00000000' NOT NULL , 
	"KTEXT" VARCHAR(60)  DEFAULT ' '        NOT NULL , 
	"LTEXT" VARCHAR(120) DEFAULT ' '        NOT NULL , 
	"MCTXT" VARCHAR(60)  DEFAULT ' '        NOT NULL 
);
