use database stg_cdc;
use warehouse cdc_wh;


/*
    스키마 확인
*/

SELECT DISTINCT TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC') ORDER BY 1;

HCS01
HTSOT01
HTSAC01
CST01
HGSIN01
STT01
HUB01
HTSML01
HTSBR01
HTSIN01
CHL01
COM01
AIR01
PKG01
HTL01
;


/*
    데이터 MERGE 프로시저 TASK 
        >> 활성화 및 비활성화
        >> 이슈 확인
*/

use database stg_cdc;
use schema public;

show tasks like '%EXECUTE_MERGE_PROC%';

select query_id, name, state, error_code, error_message, scheduled_time, query_start_time, completed_time, next_scheduled_time, query_text  
from table(information_schema.task_history())
where name like '%EXECUTE%'
order by name;

select * 
from stg_cdc.public.cdc_log
where start_time >= '2025-11-28 13:39'
;


alter task STG_CDC.PUBLIC.ETC_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.HUB01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.COM01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_01 RESUME;
alter task STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_02 RESUME;
alter task STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_01 RESUME;



alter task STG_CDC.PUBLIC.ETC_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.HUB01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.COM01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_01 SUSPEND;
alter task STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_02 SUSPEND;
alter task STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_01 SUSPEND;




/*
    스키마 별 테이블 개수, size, row count 합
*/



SELECT TABLE_SCHEMA, SUM(BYTES)/1024/1024/1024 MB, SUM(ROW_COUNT) ROW_COUNT, COUNT(*) 
FROM CDC.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC') GROUP BY TABLE_SCHEMA ORDER BY 4 ;


TABLE_SCHEMA	MB	ROW_COUNT	COUNT(*)
HCS01	      0.140318393707	3723627	     3
HTSOT01	        0.006472110748	78324	      5
HTSAC01	        0.440295696259	25579811	9
HGSIN01	        0.903395175934	21472605	21
HUB01	      0.215574741364	4127091	     25
HTSML01	        6.914710044861	683519452	25
HTSBR01	        1.452355384827	46738329	27
HTSIN01	        2.520538330078	81451629	43
CST01	      5.584228038788	231187577	18
STT01	      12.126027584076	357512117	24
CHL01	      4.439928054810	186904900	44
COM01	      0.123222827911	3133749	     69
AIR01	      37.226858615875	1111381531	72
PKG01	      89.014655590057	9743089876	74
HTL01	      6.331970691681	144382223	76
;

-- SELECT 'CALL ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || '();' SCRIPT
-- FROM INFORMATION_SCHEMA.TABLES
-- WHERE TABLE_SCHEMA = 'COM01'
-- ORDER BY TABLE_NAME;



WITH T AS (
    SELECT 
        TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME,
        BYTES,
        ROW_NUMBER() OVER (ORDER BY BYTES DESC) AS RN
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'HCS01'
)
SELECT
'CALL ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || '();' SCRIPT,
    CASE WHEN MOD(RN, 2) = 1 THEN '1' ELSE '2' END AS TARGET_TASK
FROM T
ORDER BY 2;




/*
    TASK 생성 구문
*/


CREATE OR REPLACE TASK STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_STAT_X();
CALL STG_CDC.AIR01.DSR_AIR_DSR_ISUE_X();
CALL STG_CDC.AIR01.DCD_AIR_RFD_AMT_D();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_PAY_S_M();
CALL STG_CDC.AIR01.DCD_AIR_PAY_DTRB_X();
CALL STG_CDC.AIR01.RSV_AIR_RES_STAT_D();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_M();
CALL STG_CDC.AIR01.RSV_AIR_SUPL_FEE_X();
CALL STG_CDC.AIR01.SAC_AIV_DT_PER_SBS_H();
CALL STG_CDC.AIR01.SAC_AIV_SPLY_M();
CALL STG_CDC.AIR01.RSV_AIR_ADDT_SVC_PURC_H();
CALL STG_CDC.AIR01.DSR_AIR_VOID_M();
CALL STG_CDC.AIR01.SAC_AIV_PATR_M();
CALL STG_CDC.AIR01.COM_AIR_VI_EVENT_M();
CALL STG_CDC.AIR01.COM_AIR_AIRL_M();
CALL STG_CDC.AIR01.DSR_AIR_BILG_RFD_T_X();
CALL STG_CDC.AIR01.SAC_AIV_TAXAMT_X();
CALL STG_CDC.AIR01.COM_AIR_VI_AGT_GRP_M();
CALL STG_CDC.AIR01.COM_AIR_MLG_COLT_AIRL_D();
CALL STG_CDC.AIR01.COM_AIR_VI_AGT_GRP_CRP_D();
CALL STG_CDC.AIR01.COM_AIR_EVENT_TRGT_A_D();
CALL STG_CDC.AIR01.DSR_AIR_BILG_RFD_X();
CALL STG_CDC.AIR01.COM_AIR_SEAT_CLAS_D();
CALL STG_CDC.AIR01.COM_AIR_EVENT_EXLS_TKT_D();
CALL STG_CDC.AIR01.PPD_AIR_EVENT_CD_SS_CD_D();
CALL STG_CDC.AIR01.COM_AIR_VI_AGT_GRP_D();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_FEE_X();
CALL STG_CDC.AIR01.DSR_AIR_CONJ_TKT_LST_D();
CALL STG_CDC.AIR01.RSV_INSR_JOIN_M();
CALL STG_CDC.AIR01.RSV_AIR_SLLPRC_STAT_X();
CALL STG_CDC.AIR01.DCD_AIR_ISUE_REQ_M();
CALL STG_CDC.AIR01.RSV_AIR_UNFY_RES_M();
CALL STG_CDC.AIR01.SAC_AIV_M();
CALL STG_CDC.AIR01.RSV_AIR_ONLN_CNSL_M();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_D_M();
CALL STG_CDC.AIR01.DCD_AIR_RFD_PRGS_STAT_X();
END;

CREATE OR REPLACE TASK STG_CDC.PUBLIC.AIR01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.AIR01.RSV_AIR_UNFY_RES_H();
CALL STG_CDC.AIR01.RSV_AIR_FRST_SLLPRC_X();
CALL STG_CDC.AIR01.DCD_AIR_RFD_M();
CALL STG_CDC.AIR01.DCD_AIR_RFD_SETT_AMT_D();
CALL STG_CDC.AIR01.RSV_AIR_RES_AIRSCH_X();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_SPLPRC_M();
CALL STG_CDC.AIR01.DSR_AIR_TASF_DSR_M();
CALL STG_CDC.AIR01.RSV_INSR_TKT_M();
CALL STG_CDC.AIR01.COM_AIR_EVENT_TRGT_AC_D();
CALL STG_CDC.AIR01.RSV_AIR_RES_ITNR_X();
CALL STG_CDC.AIR01.DSR_AIR_CRS_ISUE_SEG_M();
CALL STG_CDC.AIR01.PPD_AIR_EVENT_CD_M();
CALL STG_CDC.AIR01.COM_AIR_EXLS_SLS_D();
CALL STG_CDC.AIR01.DCD_AIR_RFD_TKT_X();
CALL STG_CDC.AIR01.COM_AIR_SITE_M();
CALL STG_CDC.AIR01.SAC_AIV_DT_PER_SBS_X();
CALL STG_CDC.AIR01.DSR_AIR_BILG_DSR_M();
CALL STG_CDC.AIR01.SAC_AIV_CLAS_C();
CALL STG_CDC.AIR01.DCD_AIR_CUPN_PAY_X();
CALL STG_CDC.AIR01.RSV_AIR_RES_PURC_FIX_M();
CALL STG_CDC.AIR01.DSR_AIR_BILG_CYCL_M();
CALL STG_CDC.AIR01.RSV_AIR_RES_STAT_X();
CALL STG_CDC.AIR01.RSV_AIR_PSNGR_SLLPRC_M();
CALL STG_CDC.AIR01.SAC_AIV_SPLY_RPPR_M();
CALL STG_CDC.AIR01.SAC_AIV_SPLY_SEAT_UPD_H();
CALL STG_CDC.AIR01.RSV_AIR_SRC_PNR_X();
CALL STG_CDC.AIR01.PPD_LWPRC_INFM_REQ_M();
CALL STG_CDC.AIR01.SAC_AIV_CLAS_M();
CALL STG_CDC.AIR01.SAC_AIV_SPLY_SEAT_TL_X();
CALL STG_CDC.AIR01.RSV_AIR_UNFY_RES_GRP_M();
CALL STG_CDC.AIR01.COM_AIR_EXLS_RPPR_D();
CALL STG_CDC.AIR01.DSR_AIR_BILG_ACM_ADM_X();
CALL STG_CDC.AIR01.SAC_AIV_CLAS_ATTR_M();
CALL STG_CDC.AIR01.SAC_AIV_PATR_ITNR_X();
CALL STG_CDC.AIR01.DSR_AIR_MGR_RGST_AA_X();
CALL STG_CDC.AIR01.SAC_AIV_SPLY_SEAT_DEPO_X();
END;





CREATE OR REPLACE TASK STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HTL01.SAC_HTL_RTP_ADD_FARE_D();
CALL STG_CDC.HTL01.SAC_HTL_CM_NMKUP_M();
CALL STG_CDC.HTL01.COM_HTL_ROOM_C();
CALL STG_CDC.HTL01.RSV_HTL_RES_CMPLN_D();
CALL STG_CDC.HTL01.SAC_SUPL_HTL_SRC_M();
CALL STG_CDC.HTL01.SLP_HTL_LBL_MGMT_M();
CALL STG_CDC.HTL01.SAC_SPLY_HTL_RPPR_D();
CALL STG_CDC.HTL01.COM_HTL_EAN_CITY_GTHR_X();
CALL STG_CDC.HTL01.SAC_HTL_FARE_GRP_M();
CALL STG_CDC.HTL01.RSV_HTL_RES_L();
CALL STG_CDC.HTL01.SAC_TRPADV_HTL_MAPP_D();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_MKUP_CHNL_D();
CALL STG_CDC.HTL01.RSV_CUPN_USE_DESC_D();
CALL STG_CDC.HTL01.SAC_SUPL_CITY_MAPP_M();
CALL STG_CDC.HTL01.RSV_HTL_RES_ADD_FARE_D();
CALL STG_CDC.HTL01.RSV_HTL_RES_UPD_H();
CALL STG_CDC.HTL01.RSV_HTL_ROOM_RES_D();
CALL STG_CDC.HTL01.SAC_HTL_INV_FARE_D();
CALL STG_CDC.HTL01.SLP_SLCO_VI_CMTN_BASS_M();
CALL STG_CDC.HTL01.COM_HTL_CHAN_C();
CALL STG_CDC.HTL01.COM_HTL_XPEDIA_I();
CALL STG_CDC.HTL01.SAC_HTL_LDMK_D();
CALL STG_CDC.HTL01.SLP_HTL_SALE_PROM_GOAL_M();
CALL STG_CDC.HTL01.COM_HTL_SUPL_BASS_MGMT_M();
CALL STG_CDC.HTL01.COM_HTL_EAN_LDMK_GTHR_X();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_CHNL_D();
CALL STG_CDC.HTL01.COM_HTL_CHNL_C();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_CNTRY_D();
CALL STG_CDC.HTL01.RSV_DPURC_PKG_RES_M();
CALL STG_CDC.HTL01.SAC_HTL_RTP_BNFT_D();
CALL STG_CDC.HTL01.COM_HTL_C();
CALL STG_CDC.HTL01.RSV_HTL_RES_ORDR_INFO_X();
CALL STG_CDC.HTL01.RSV_HTL_RES_H();
CALL STG_CDC.HTL01.SAC_HTL_BSC_NMKUP_M();
CALL STG_CDC.HTL01.SAC_HTL_ROOM_D();
CALL STG_CDC.HTL01.SAC_HTL_SPCL_PROM_D();
CALL STG_CDC.HTL01.SAC_HTL_RTP_DESC_D();
CALL STG_CDC.HTL01.SAC_SUPL_HTL_MAPP_M();
END;





CREATE OR REPLACE TASK STG_CDC.PUBLIC.HTL01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_MKUP_D();
CALL STG_CDC.HTL01.SLP_SUPL_VI_CMTN_BASS_M();
CALL STG_CDC.HTL01.SAC_HTL_CRPN_SLPRC_RVNS_M();
CALL STG_CDC.HTL01.SLP_HTL_SALE_PROM_M();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_TYPE_M();
CALL STG_CDC.HTL01.SLP_SUPL_VI_GOAL_D();
CALL STG_CDC.HTL01.SAC_HTL_SLPRC_RVNS_D();
CALL STG_CDC.HTL01.COM_HTL_XPEDIA_MAPP_X();
CALL STG_CDC.HTL01.SAC_HTL_PROM_RTP_R();
CALL STG_CDC.HTL01.SAC_HTL_CM_INV_BLK_D();
CALL STG_CDC.HTL01.SAC_SUPL_HTL_M();
CALL STG_CDC.HTL01.RSV_HTL_RES_PROM_D();
CALL STG_CDC.HTL01.SAC_HTL_RTP_M();
CALL STG_CDC.HTL01.RSV_HTL_LDGR_D();
CALL STG_CDC.HTL01.RSV_HTL_AFCN_ORDR_INFO_X();
CALL STG_CDC.HTL01.SAC_HTL_INV_BLK_D();
CALL STG_CDC.HTL01.RSV_HTL_RES_FARE_D();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_DC_CHNL_D();
CALL STG_CDC.HTL01.SAC_HTL_NMKUP_D();
CALL STG_CDC.HTL01.SAC_HTL_CM_SLPRC_RVNS_D();
CALL STG_CDC.HTL01.COM_HTL_SUPL_BASS_MGMT_D();
CALL STG_CDC.HTL01.COM_HTL_EAN_BAS_C();
CALL STG_CDC.HTL01.SAC_HTL_ADD_FARE_D();
CALL STG_CDC.HTL01.COM_HTL_CHNL_FER_BASS_C();
CALL STG_CDC.HTL01.COM_HTL_HASHTAG_M();
CALL STG_CDC.HTL01.SLP_HTL_SLPRC_DC_D();
CALL STG_CDC.HTL01.SLP_SUPL_VI_AREA_D();
CALL STG_CDC.HTL01.COM_HTL_CITY_LDMK_M();
CALL STG_CDC.HTL01.SAC_HTL_PROM_D();
CALL STG_CDC.HTL01.SLP_SLCO_VI_GOAL_D();
CALL STG_CDC.HTL01.SAC_HTL_RTP_CHNL_D();
CALL STG_CDC.HTL01.COM_HTL_CNTRY_ROUT_C();
CALL STG_CDC.HTL01.SLP_HTL_SVLM_S();
CALL STG_CDC.HTL01.RSV_HTL_RES_D();
CALL STG_CDC.HTL01.SAC_CRPN_SPLY_HTL_M();
CALL STG_CDC.HTL01.SAC_EAN_REVIEW_D();
CALL STG_CDC.HTL01.SAC_SPLY_HTL_M();
CALL STG_CDC.HTL01.SAC_HTL_ROOM_RTP_R();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.PKG01.PDS_PKG_LND_COST_R();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_SHPN_D();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_THM_D();
CALL STG_CDC.PKG01.COM_PKG_PROD_SPRTR_C();
CALL STG_CDC.PKG01.RSV_PKG_RES_UPD_D();
CALL STG_CDC.PKG01.PPD_PKG_RPPD_CNTNT_D();
CALL STG_CDC.PKG01.PPD_PKG_RPPD_M();
CALL STG_CDC.PKG01.RSV_PKG_BFHD_ISUE_MGMT_D();
CALL STG_CDC.PKG01.PPD_PKG_GUID_AGSN_M();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_UPD_H();
CALL STG_CDC.PKG01.PDS_PKG_LND_COST_DTL_R();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_ITNR_CITY_D();
CALL STG_CDC.PKG01.PDS_PKG_LND_COST_SETT_M();
CALL STG_CDC.PKG01.RSV_PKG_TRVL_CNDM_AGRT_D();
CALL STG_CDC.PKG01.PPD_PKG_SNDG_M();
CALL STG_CDC.PKG01.RSV_PKG_RES_UPD_L();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_SCHD_LAND_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_CTRC_M();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_RCCT_D();
CALL STG_CDC.PKG01.PPD_PKG_SNDG_PRPN_M();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_BROF_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_SCHD_D();
CALL STG_CDC.PKG01.RSV_PKG_RES_D();
CALL STG_CDC.PKG01.RSV_PKG_RES_M();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_M();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_SCHD_GOFC_D();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_HTL_D();
CALL STG_CDC.PKG01.COM_PKG_AREA_C();
CALL STG_CDC.PKG01.PPD_PKG_RPPD_VIST_CITY_D();
CALL STG_CDC.PKG01.PPD_AI_SCHD_M();
CALL STG_CDC.PKG01.PPD_PKG_RVNS_DEPT_M();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_ANSR_SEND_H();
CALL STG_CDC.PKG01.PPD_PKG_TC_PRAR_INFO_M();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_DAY_D();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_CNTNT_D();
CALL STG_CDC.PKG01.PDS_PKG_LND_COST_FNSMT_M();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_SCHD_D();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.PKG01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.PKG01.RSV_PKG_QUOT_M();
CALL STG_CDC.PKG01.SAC_PKG_SPPD_GOLF_D();
CALL STG_CDC.PKG01.PPD_AI_SCHD_TMPL_M();
CALL STG_CDC.PKG01.PPD_PKG_SIM_M();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_BIDN_M();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_M();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_D();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_SPCL_STPL_D();
CALL STG_CDC.PKG01.RSV_PKG_FLXB_AMT_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_SCHD_M();
CALL STG_CDC.PKG01.RSV_PKG_RES_RMK_D();
CALL STG_CDC.PKG01.RSV_PKG_CLPSN_PECN_S();
CALL STG_CDC.PKG01.PPD_PKG_TC_ASGN_X();
CALL STG_CDC.PKG01.COM_PKG_GUID_WRDNG_C();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_NTYT_CNTG_D();
CALL STG_CDC.PKG01.COM_PKG_TRVL_EXPN_C();
CALL STG_CDC.PKG01.PPD_PKG_PROD_MSTR_M();
CALL STG_CDC.PKG01.PPD_PKG_RPPD_TAG_D();
CALL STG_CDC.PKG01.COM_PKG_SHPN_CNTR_M();
CALL STG_CDC.PKG01.PPD_PKG_RPPD_MSTR_R();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_RSPB_D();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_SCHD_HTL_D();
CALL STG_CDC.PKG01.PPD_PKG_PROD_CTPR_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_SIM_R();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_AIR_INV_X();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_PROD_D();
CALL STG_CDC.PKG01.COM_PKG_CHC_STSNG_M();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_JNT_EVNT_C();
CALL STG_CDC.PKG01.PPD_PKG_GUID_AGSN_D();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_DMND_D();
CALL STG_CDC.PKG01.RSV_PKG_QUOT_MGR_M();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_SHPSHP_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_GDWD_D();
CALL STG_CDC.PKG01.PPD_PKG_SALE_PROD_THM_D();
CALL STG_CDC.PKG01.PDS_PKG_LND_COST_INVC_M();
CALL STG_CDC.PKG01.PPD_PKG_SLPD_PROM_D();
END;




CREATE OR REPLACE TASK STG_CDC.PUBLIC.COM01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.COM01.USR_MENU_ACES_H();
CALL STG_CDC.COM01.RSV_BKR_M();
CALL STG_CDC.COM01.RSV_RES_COM_ATTR_D();
CALL STG_CDC.COM01.SCH_AGT_D();
CALL STG_CDC.COM01.USR_UNFY_USR_M();
CALL STG_CDC.COM01.SCH_PTN_M();
CALL STG_CDC.COM01.SCH_CARD_BIN_M();
CALL STG_CDC.COM01.COM_IATA_APT_C();
CALL STG_CDC.COM01.COM_COOP_EMP_M();
CALL STG_CDC.COM01.SCH_LAND_DEPT_D();
CALL STG_CDC.COM01.SCH_AGT_PKG_SALS_RSPB_D();
CALL STG_CDC.COM01.SCH_CCCO_D();
CALL STG_CDC.COM01.SCH_OVRS_PTN_R();
CALL STG_CDC.COM01.USR_UNFY_DEPT_C();
CALL STG_CDC.COM01.RSV_BKR_TUST_AGRT_D();
CALL STG_CDC.COM01.COM_COM_DTL_C();
CALL STG_CDC.COM01.SCH_UNFY_CRPN_LAND_R();
CALL STG_CDC.COM01.COM_EMP_M();
CALL STG_CDC.COM01.SCH_BSP_PTN_X();
CALL STG_CDC.COM01.COM_COM_BSC_C();
CALL STG_CDC.COM01.SCH_LAND_D();
CALL STG_CDC.COM01.COM_CNTRY_C();
CALL STG_CDC.COM01.RSV_RES_UNFY_R();
CALL STG_CDC.COM01.SCH_OVRS_CRPN_STAF_D();
CALL STG_CDC.COM01.RSV_TUST_ADDT_INFO_D();
CALL STG_CDC.COM01.COM_CNTRY_MTLG_C();
CALL STG_CDC.COM01.SCH_LAND_ADD_D();
CALL STG_CDC.COM01.SCH_OVRS_CRPN_ADD_D();
CALL STG_CDC.COM01.SCH_LAND_CTRC_R();
CALL STG_CDC.COM01.COM_GG_C();
CALL STG_CDC.COM01.SCH_PTN_RPPR_R();
CALL STG_CDC.COM01.SCH_OVRS_PTN_D();
CALL STG_CDC.COM01.SCH_PTN_R();
CALL STG_CDC.COM01.COM_CAL_C();
CALL STG_CDC.COM01.USR_EXTR_USR_M();
CALL STG_CDC.COM01.RSV_RES_COM_M();
CALL STG_CDC.COM01.SCH_PTN_RLTC_R();
CALL STG_CDC.COM01.SCH_AIR_SUPL_D();
CALL STG_CDC.COM01.COM_STATE_MTLG_C();
CALL STG_CDC.COM01.COM_COM_DTL_MTLG_C();
CALL STG_CDC.COM01.COM_SVC_RUL_M();
CALL STG_CDC.COM01.SCH_BZMN_INFO_C();
CALL STG_CDC.COM01.COM_FER_M();
CALL STG_CDC.COM01.USR_USR_ACNT_M();
CALL STG_CDC.COM01.USR_USR_ATHR_R();
CALL STG_CDC.COM01.RSV_TUST_M();
CALL STG_CDC.COM01.SCH_AGT_GRAD_D();
CALL STG_CDC.COM01.SCH_OVRS_PTN_STAF_D();
CALL STG_CDC.COM01.SCH_AGT_HNRP_D();
CALL STG_CDC.COM01.SCH_AGT_CTRC_R();
CALL STG_CDC.COM01.SCH_PTN_STAF_D();
CALL STG_CDC.COM01.USR_UNFY_USC_PROF_DPC_D();
CALL STG_CDC.COM01.SCH_OVRS_PTN_M();
CALL STG_CDC.COM01.COM_ROAD_NM_ADRS_C();
CALL STG_CDC.COM01.SCH_OVRS_PTN_ADD_D();
CALL STG_CDC.COM01.USR_UNFY_USR_COM_C();
CALL STG_CDC.COM01.COM_CITY_C();
CALL STG_CDC.COM01.COM_FRST_NTFC_FER_X();
CALL STG_CDC.COM01.SCH_OVRS_CRPN_INFO_M();
CALL STG_CDC.COM01.COM_MLG_MGMT_M();
CALL STG_CDC.COM01.SCH_PTN_CTRC_REL_C();
CALL STG_CDC.COM01.RSV_BKR_ADDT_INFO_D();
CALL STG_CDC.COM01.RSV_RES_RPPR_D();
CALL STG_CDC.COM01.COM_EXST_ZIP_C();
CALL STG_CDC.COM01.SCH_SCO_AGT_M();
CALL STG_CDC.COM01.COM_DEPT_C();
CALL STG_CDC.COM01.SCH_UNFY_CRPN_SYS_D();
CALL STG_CDC.COM01.COM_STATE_C();
CALL STG_CDC.COM01.COM_CITY_MTLG_C();
END;




CREATE OR REPLACE TASK STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.CHL01.MPS_CUPN_MSTR_M();
CALL STG_CDC.CHL01.COT_FAQ_INFO_MGMT_M();
CALL STG_CDC.CHL01.CTS_CNTNT_ADIF_M();
CALL STG_CDC.CHL01.CTS_PROD_LDG_M();
CALL STG_CDC.CHL01.CDM_CARD_GRP_R();
CALL STG_CDC.CHL01.MPS_EVENT_APCT_D();
CALL STG_CDC.CHL01.MPS_CUPN_REL_COND_D();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_PROD_CATG_D();
CALL STG_CDC.CHL01.COM_BNR_MGMT_COND_D();
CALL STG_CDC.CHL01.CDM_CARD_GRP_M();
CALL STG_CDC.CHL01.CTS_CNTNT_CATG_M();
CALL STG_CDC.CHL01.CTS_CNTNT_CATG_MTLG_D();
CALL STG_CDC.CHL01.CTS_PROD_GOFC_MTLG_D();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_AGT_D();
CALL STG_CDC.CHL01.COM_BNR_MGMT_M();
CALL STG_CDC.CHL01.CTS_LCM_BRD_M();
CALL STG_CDC.CHL01.COM_SHCR_INFO_M();
CALL STG_CDC.CHL01.CTS_CNTNT_AREA_D();
CALL STG_CDC.CHL01.COM_DTCM_SVC_STPL_M();
CALL STG_CDC.CHL01.COM_CITY_CATG_M();
CALL STG_CDC.CHL01.MPS_DAR_CATG_M();
CALL STG_CDC.CHL01.MPS_DAR_M();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.CHL01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.CHL01.CTS_LCM_INFM_REQ_X();
CALL STG_CDC.CHL01.MPS_CUST_CUPN_ISNC_D();
CALL STG_CDC.CHL01.CTS_RSRC_IMG_M();
CALL STG_CDC.CHL01.CTS_CNTNT_ADIF_IMG_R();
CALL STG_CDC.CHL01.CDM_CARD_M();
CALL STG_CDC.CHL01.CTS_PROD_OPTN_PROD_M();
CALL STG_CDC.CHL01.CDM_CARD_CLST_M();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_PROD_GRP_D();
CALL STG_CDC.CHL01.CTS_CNTNT_GPS_D();
CALL STG_CDC.CHL01.CTS_PROD_GOFC_M();
CALL STG_CDC.CHL01.CTS_CNTNT_M();
CALL STG_CDC.CHL01.CTS_CNTNT_MTLG_D();
CALL STG_CDC.CHL01.MPS_EVENT_INFO_M();
CALL STG_CDC.CHL01.PDP_DTCM_RCMN_PLNN_EXHT_R();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_FLTR_M();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_PROD_D();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_INFO_M();
CALL STG_CDC.CHL01.PDP_PLNN_EXHT_INFO_FLTR_D();
CALL STG_CDC.CHL01.MPS_CUST_MRCP_D();
CALL STG_CDC.CHL01.COM_SRWR_MGMT_M();
CALL STG_CDC.CHL01.PDP_AFCN_RCMN_PLNN_EXHT_R();
CALL STG_CDC.CHL01.CDM_TMPL_M();
END;




CREATE OR REPLACE TASK STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.STT01.DEP_CARD_AUTH_M();
CALL STG_CDC.STT01.SET_LND_COST_SETT_D();
CALL STG_CDC.STT01.SET_IDVL_EXPN_SETT_D();
CALL STG_CDC.STT01.SET_JNT_EXPN_SETT_D();
CALL STG_CDC.STT01.REC_UNCL_RFD_RES_S();
CALL STG_CDC.STT01.DEP_DEPR_NM_X();
CALL STG_CDC.STT01.FSU_COM_BSC_C();
CALL STG_CDC.STT01.SET_NSTG_SETT_M();
CALL STG_CDC.STT01.SET_LND_COST_RFD_D();
CALL STG_CDC.STT01.SET_TKT_SETT_FEE_X();
CALL STG_CDC.STT01.DEP_UNFY_RECM_PAY_X();
CALL STG_CDC.STT01.FSU_COM_DTL_C();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.STT01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.STT01.FSU_SETT_ACNT_CD_C();
CALL STG_CDC.STT01.REC_UNCL_RES_S();
CALL STG_CDC.STT01.SET_PROD_SETT_M();
CALL STG_CDC.STT01.DEP_CARD_AUTH_D();
CALL STG_CDC.STT01.SET_TKT_SETT_X();
CALL STG_CDC.STT01.FSU_CLSG_X();
CALL STG_CDC.STT01.SET_SETT_APRV_D();
CALL STG_CDC.STT01.SET_SETT_APRV_M();
CALL STG_CDC.STT01.SET_AIR_SETT_D();
CALL STG_CDC.STT01.SET_AIR_APRV_D();
CALL STG_CDC.STT01.FSU_USR_ATHR_M();
CALL STG_CDC.STT01.SET_LND_RFD_SETT_X();
END;



CREATE OR REPLACE TASK STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.CST01.CST_MEM_M();
CALL STG_CDC.CST01.CST_NNMM_M();
CALL STG_CDC.CST01.CST_MEM_GRAD_D();
CALL STG_CDC.CST01.CST_MEM_JNNG_X();
CALL STG_CDC.CST01.CST_SCSN_MEM_M();
CALL STG_CDC.CST01.CST_DL_CUST_M();
CALL STG_CDC.CST01.CST_DSTRY_CUST_M();
CALL STG_CDC.CST01.CST_MEM_AGRT_X();
CALL STG_CDC.CST01.CST_MEM_CNCR_AITM_D();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.CST01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.CST01.CST_MEM_LGN_D();
CALL STG_CDC.CST01.CST_MEM_AMITY_AGT_D();
CALL STG_CDC.CST01.CST_MEM_UPD_REQ_X();
CALL STG_CDC.CST01.CST_INAT_MEM_LGN_D();
CALL STG_CDC.CST01.CST_MEM_ADRS_D();
CALL STG_CDC.CST01.CST_MEM_PTNS_M();
CALL STG_CDC.CST01.CST_MEM_UPD_H();
CALL STG_CDC.CST01.CST_INAT_MEM_M();
CALL STG_CDC.CST01.CST_MEM_STAF_FAML_R();
END;



CREATE OR REPLACE TASK STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HTSML01.APR_DEALTR_TRN();
CALL STG_CDC.HTSML01.SAVE_FIFO_TRN();
CALL STG_CDC.HTSML01.USE_DEALTR_DTL();
CALL STG_CDC.HTSML01.CST_SVC_TRN();
CALL STG_CDC.HTSML01.CST_JOINGROUP_MGT();
CALL STG_CDC.HTSML01.USE_FIFO_DIV();
CALL STG_CDC.HTSML01.MCT_MASTER_MST();
CALL STG_CDC.HTSML01.EXP_MLG_BATSTD_WRK();
CALL STG_CDC.HTSML01.CST_GRUP_MST();
CALL STG_CDC.HTSML01.JOIN_DEALTR_DIV();
CALL STG_CDC.HTSML01.CST_PNT_MST();
CALL STG_CDC.HTSML01.CST_SUB_MEM();
CALL STG_CDC.HTSML01.CDE_MASTER();
END;


CREATE OR REPLACE TASK STG_CDC.PUBLIC.HTSML01_EXECUTE_MERGE_PROC_02
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HTSML01.CDE_CATEGORY();
CALL STG_CDC.HTSML01.SAVE_FIFO_DIV();
CALL STG_CDC.HTSML01.CST_INTERFACE_LOG();
CALL STG_CDC.HTSML01.USE_FIFO_TRN();
CALL STG_CDC.HTSML01.APR_DEALTR_DTL();
CALL STG_CDC.HTSML01.JOIN_MASTER_MST();
CALL STG_CDC.HTSML01.PRO_NOTICE_SVC();
CALL STG_CDC.HTSML01.CST_MASTER_MST();
CALL STG_CDC.HTSML01.PNT_SUM_MST();
CALL STG_CDC.HTSML01.CST_SCS_MAP();
CALL STG_CDC.HTSML01.PTNS_BATSTD_WRK();
CALL STG_CDC.HTSML01.JOIN_CARD_MST();
END;




CREATE OR REPLACE TASK STG_CDC.PUBLIC.HUB01_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HUB01.VOC_DMND_M();
CALL STG_CDC.HUB01.SCH_PTN_MAIN_SCRN_CONF_H();
CALL STG_CDC.HUB01.VOC_DTRB_HIST_ADD_D();
CALL STG_CDC.HUB01.VOC_PRS_H();
CALL STG_CDC.HUB01.CRP_RSPB_AGT_M();
CALL STG_CDC.HUB01.CRP_RSPB_TYPE_PER_RPPR_D();
CALL STG_CDC.HUB01.CRP_CRPN_RPPR_M();
CALL STG_CDC.HUB01.CSI_RSC_SVR_M();
CALL STG_CDC.HUB01.CRP_CRPN_MEM_MLG_MST_M();
CALL STG_CDC.HUB01.SCH_PTN_STAF_ADD_D();
CALL STG_CDC.HUB01.VOC_STDG_M();
CALL STG_CDC.HUB01.CRP_RSPB_AGT_STAF_D();
CALL STG_CDC.HUB01.SCH_MEMC_SITE_C();
CALL STG_CDC.HUB01.SCH_PNT_TSUM_M();
CALL STG_CDC.HUB01.VOC_CMPN_H();
CALL STG_CDC.HUB01.VOC_DMND_TYPE_R();
CALL STG_CDC.HUB01.CSI_OVP_SVR_M();
CALL STG_CDC.HUB01.VOC_CATG_SSC_R();
CALL STG_CDC.HUB01.VOC_SHPN_RFD_H();
CALL STG_CDC.HUB01.CRP_CMNTY_M();
CALL STG_CDC.HUB01.VOC_UP_CATG_R();
CALL STG_CDC.HUB01.VOC_CATG_C();
CALL STG_CDC.HUB01.VOC_DMND_EXNS_M();
CALL STG_CDC.HUB01.VOC_DTRB_H();
CALL STG_CDC.HUB01.CRP_CRPN_MAIN_M();
END;



CREATE OR REPLACE TASK STG_CDC.PUBLIC.ETC_EXECUTE_MERGE_PROC_01
WAREHOUSE = CDC_WH
SCHEDULE = 'USING CRON 40 * * * * Asia/Seoul'
AS 
BEGIN
CALL STG_CDC.HTSIN01.COOP_RES();
CALL STG_CDC.HTSIN01.COOP_RES_PRD();
CALL STG_CDC.HTSIN01.OUT_CONFIRM();
CALL STG_CDC.HTSIN01.CST_HP_RCT();
CALL STG_CDC.HTSIN01.BRC_CURR_INFO();
CALL STG_CDC.HTSIN01.DAT_SYS_USER();
CALL STG_CDC.HTSIN01.CST_MLG_IF();
CALL STG_CDC.HTSIN01.BRANCH_COMP_OPRT_SUB();
CALL STG_CDC.HTSIN01.BRANCH_COMP_OPRT_MST();
CALL STG_CDC.HTSIN01.BRC_GOAL_INFO();
CALL STG_CDC.HTSIN01.CST_PROPERTY_INFO();
CALL STG_CDC.HTSIN01.PUB_ETCCODE();
CALL STG_CDC.HTSIN01.TLT_ETCCODE();
CALL STG_CDC.HTSIN01.BRANCH_COMP_OPRT_CODE();
CALL STG_CDC.HTSIN01.BUS_WORK_PLACE();
CALL STG_CDC.HTSIN01.COOP_RES_BKR();
CALL STG_CDC.HTSIN01.CST_REQ_INFO();
CALL STG_CDC.HTSIN01.CST_PRPT_INFO();
CALL STG_CDC.HTSIN01.OUT_SETT();
CALL STG_CDC.HTSIN01.BG_CATEGORY_EMP_CONFIG();
CALL STG_CDC.HTSIN01.CST_AGREE_SIGN();
CALL STG_CDC.HTSIN01.BRC_GOAL_DETAIL();
CALL STG_CDC.HTSIN01.BRC_WEEK_INFO();
CALL STG_CDC.HTSIN01.BUS_ETCCODE();
CALL STG_CDC.HTSIN01.CST_EVENT_REMARK();
CALL STG_CDC.HTSIN01.COOP_RES_CUS();
CALL STG_CDC.HTSIN01.BRC_PUB_ETCCODE();
CALL STG_CDC.HTSIN01.CST_CLT_AGRMT();
CALL STG_CDC.HTSIN01.EDI2_MASTER();
CALL STG_CDC.HTSIN01.CST_SCHD_INFO();
CALL STG_CDC.HTSIN01.GIFT_RET_DET();
CALL STG_CDC.HTSIN01.BG_BUS_EMPLOYEE_MNG();
CALL STG_CDC.HTSIN01.BRC_INFO();
CALL STG_CDC.HTSIN01.ITEM_OUT_MASTER();
CALL STG_CDC.HTSIN01.BRC_CORP_INFO();
CALL STG_CDC.HTSIN01.ITEM_MASTER();
CALL STG_CDC.HTSIN01.ITEM_STOCK_SUMMARY();
CALL STG_CDC.HTSIN01.CST_CODE();
CALL STG_CDC.HTSIN01.COM_DEPT_PKG();
CALL STG_CDC.HTSIN01.DAT_SYS_AUTH();
CALL STG_CDC.HTSIN01.OUT_SETT_ITEM();
CALL STG_CDC.HTSIN01.EDI2_DOC_TYPE();
CALL STG_CDC.HTSIN01.EDI2_DOC_CODE();
CALL STG_CDC.HTSBR01.GN_SET_PKG_MST();
CALL STG_CDC.HTSBR01.GN_SET_PKG_MISC();
CALL STG_CDC.HTSBR01.GN_PKG_OB_PKG();
CALL STG_CDC.HTSBR01.GN_PKG_GRP_PRE();
CALL STG_CDC.HTSBR01.CDE_CTG_BIG();
CALL STG_CDC.HTSBR01.GN_SET_PKG_AIR();
CALL STG_CDC.HTSBR01.GN_SET_HTL_MST();
CALL STG_CDC.HTSBR01.GN_SET_TKT_MST();
CALL STG_CDC.HTSBR01.GN_SET_PKG_OB_AIR();
CALL STG_CDC.HTSBR01.CDE_CTG_SML();
CALL STG_CDC.HTSBR01.CDE_CTG_DET();
CALL STG_CDC.HTSBR01.GN_PKG_MAIN();
CALL STG_CDC.HTSBR01.GN_SET_PKG_OB_MST();
CALL STG_CDC.HTSBR01.GN_PKG_AGENCY();
CALL STG_CDC.HTSBR01.GN_PKG_CHEQUE();
CALL STG_CDC.HTSBR01.GN_CONN_MOBILE_LOG();
CALL STG_CDC.HTSBR01.GN_PKG_TOUR_FEE();
CALL STG_CDC.HTSBR01.GN_CDE_CUST();
CALL STG_CDC.HTSBR01.GN_PKG_HOTEL();
CALL STG_CDC.HTSBR01.GN_PKG_TKT_USE();
CALL STG_CDC.HTSBR01.GN_ACC_REC();
CALL STG_CDC.HTSBR01.GN_PKG_COACH();
CALL STG_CDC.HTSBR01.GN_SET_PKG_OB_DET();
CALL STG_CDC.HTSBR01.CDE_CTG_MED();
CALL STG_CDC.HTSBR01.GN_SET_AIRTEL_MST();
CALL STG_CDC.HTSBR01.CDE_MAIDAS_CODE();
CALL STG_CDC.HTSBR01.ACC_SLP_DTL();
CALL STG_CDC.HGSIN01.COM_HTL_RES();
CALL STG_CDC.HGSIN01.PUB_AREA();
CALL STG_CDC.HGSIN01.AGT_MEMBER();
CALL STG_CDC.HGSIN01.COM_PKG_GOODS();
CALL STG_CDC.HGSIN01.PUB_COUNTRY();
CALL STG_CDC.HGSIN01.COM_INDIVI_GOODS();
CALL STG_CDC.HGSIN01.CDE_HOTEL_CHAIN();
CALL STG_CDC.HGSIN01.COM_PKG_RES();
CALL STG_CDC.HGSIN01.DSR_MASTER();
CALL STG_CDC.HGSIN01.COM_INDIVI_RES();
CALL STG_CDC.HGSIN01.COM_HTL_RES_CFM();
CALL STG_CDC.HGSIN01.COM_ETC_RES();
CALL STG_CDC.HGSIN01.COM_LANDJOIN_DET();
CALL STG_CDC.HGSIN01.OL_ESTI_FILE();
CALL STG_CDC.HGSIN01.NG_COMP_MGR();
CALL STG_CDC.HGSIN01.COM_LAND();
CALL STG_CDC.HGSIN01.AGT_AGENT();
CALL STG_CDC.HGSIN01.PUB_CITY();
CALL STG_CDC.HGSIN01.GUIDE_POOL_DET();
CALL STG_CDC.HGSIN01.COM_SALES_INFO();
CALL STG_CDC.HGSIN01.DAT_LDG_CITEM();
CALL STG_CDC.HTSAC01.ACC_SLP_MST();
CALL STG_CDC.HTSAC01.ACC_ACT();
CALL STG_CDC.HTSAC01.CDE_CM_DTL();
CALL STG_CDC.HTSAC01.CDE_CM_MST();
CALL STG_CDC.HTSAC01.ACC_BNK_MST();
CALL STG_CDC.HTSAC01.EMP_INFO();
CALL STG_CDC.HTSAC01.ACC_EXH();
CALL STG_CDC.HTSAC01.ACC_ACTTT();
CALL STG_CDC.HTSAC01.DEPT_INFO();
CALL STG_CDC.HTSOT01.MST_BUS_REG();
CALL STG_CDC.HTSOT01.DAT_TRADE_MST();
CALL STG_CDC.HTSOT01.DAT_BUS_REG();
CALL STG_CDC.HTSOT01.MST_COMPANY();
CALL STG_CDC.HTSOT01.CDE_PRD_TYPE();
CALL STG_CDC.HCS01.UC_CRS_CONSL_HIST();
CALL STG_CDC.HCS01.UC_SYS_CODEBOOK();
CALL STG_CDC.HCS01.UC_SYS_USER();
END;





