USE ROLE ACCOUNTADMIN;
 
 
CREATE USER H2122
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'H2122'
  DISPLAY_NAME = '이영규'
  EMAIL = 'itsme@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER H2122;
GRANT ROLE ACCOUNTADMIN TO USER H2122;
GRANT ROLE USERADMIN TO USER H2122;
GRANT ROLE SECURITYADMIN TO USER H2122;
 
CREATE USER H2640
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'H2640'
  DISPLAY_NAME = '문형서'
  EMAIL = 'ronny213@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER H2640;
GRANT ROLE ACCOUNTADMIN TO USER H2640;
GRANT ROLE USERADMIN TO USER H2640;
GRANT ROLE SECURITYADMIN TO USER H2640;
 
CREATE USER HG548
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HG548'
  DISPLAY_NAME = '박준석C'
  EMAIL = 'karistma@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HG548;
GRANT ROLE ACCOUNTADMIN TO USER HG548;
GRANT ROLE USERADMIN TO USER HG548;
GRANT ROLE SECURITYADMIN TO USER HG548;
 
CREATE USER HG376
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HG376'
  DISPLAY_NAME = '정진혜'
  EMAIL = '6863jh@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HG376;
GRANT ROLE ACCOUNTADMIN TO USER HG376;
GRANT ROLE USERADMIN TO USER HG376;
GRANT ROLE SECURITYADMIN TO USER HG376;
 
CREATE USER HI036
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HI036'
  DISPLAY_NAME = '백승현'
  EMAIL = 'shb413@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HI036;
GRANT ROLE ACCOUNTADMIN TO USER HI036;
GRANT ROLE USERADMIN TO USER HI036;
GRANT ROLE SECURITYADMIN TO USER HI036;
 
CREATE USER HI040
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HI040'
  DISPLAY_NAME = '곽도영'
  EMAIL = 'kdy6379@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HI040;
GRANT ROLE ACCOUNTADMIN TO USER HI040;
GRANT ROLE USERADMIN TO USER HI040;
GRANT ROLE SECURITYADMIN TO USER HI040;
 
-- 확인
SHOW USERS LIKE 'H%';
 
/*일반 사용자
HG282 서재영 jayseo@hanatour.com
HB520 한상민 hbs1229@hanatour.com
HG256 박서원 abenu@hanatour.com
*/
CREATE USER HG282
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HG282'
  DISPLAY_NAME = '서재영'
  EMAIL = 'jayseo@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HG282;
GRANT ROLE ACCOUNTADMIN TO USER HG282;
GRANT ROLE USERADMIN TO USER HG282;
GRANT ROLE SECURITYADMIN TO USER HG282;
 
CREATE USER HB520
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HB520'
  DISPLAY_NAME = '한상민'
  EMAIL = 'hbs1229@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HB520;
 
CREATE USER HG256
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HG256'
  DISPLAY_NAME = '박서원'
  EMAIL = 'abenu@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HG256;
 
 
CREATE USER HG384
  PASSWORD = 'HanaTour123!@#'
  LOGIN_NAME = 'HG384'
  DISPLAY_NAME = '신현철'
  EMAIL = 'n2spunky@hanatour.com'
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER HG384;