use role sysadmin;

CREATE DATABASE SYS_SECURITY COMMENT = '보안정책 DB';
CREATE SCHEMA SYS_SECURITY.HNT_POLICY COMMENT = '보안정책 SCHEMA';
drop SCHEMA SYS_SECURITY.sys_POLICY;
drop SCHEMA SECURITY.MHS_POLICY; -- 이거 안돼. 마스킹해제 후에 가능.
