-- ACCOUNT 의 Snowflake 기능 사용량 조회
SELECT * FROM MZC_BILLING.BILLING_USAGE.USAGE_IN_CURRENCY_DAILY;


-- 웨어하우스 크레딧 소모량 조회
SELECT 
    TO_DATE(START_TIME) AS USAGE_DATE,
    WAREHOUSE_NAME,                                    
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,        
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE 
    START_TIME >= DATEADD('day', -10, CURRENT_DATE())  
GROUP BY 
    1, 2                                              
ORDER BY 
    USAGE_DATE DESC,                               
    TOTAL_CREDITS DESC;      